// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FishEscapeReason.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from FishEscapeReason.proto</summary>
  public static partial class FishEscapeReasonReflection {

    #region Descriptor
    /// <summary>File descriptor for FishEscapeReason.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FishEscapeReasonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZGaXNoRXNjYXBlUmVhc29uLnByb3RvKnoKEEZpc2hFc2NhcGVSZWFzb24S",
            "JwojRklTSF9FU0NBUEVfUkVBU09OX0ZJU05fRVNDQVBFX05PTkUQABIeChpG",
            "SVNIX0VTQ0FQRV9SRUFTT05fU0hPQ0tFRBABEh0KGUZJU0hfRVNDQVBFX1JF",
            "QVNPTl9VTkhPT0sQAkIiqgIfV2VlZHdhY2tlci5TaGFyZWQuTmV0d29yay5Q",
            "cm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Weedwacker.Shared.Network.Proto.FishEscapeReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FishEscapeReason {
    [pbr::OriginalName("FISH_ESCAPE_REASON_FISN_ESCAPE_NONE")] FisnEscapeNone = 0,
    [pbr::OriginalName("FISH_ESCAPE_REASON_SHOCKED")] Shocked = 1,
    [pbr::OriginalName("FISH_ESCAPE_REASON_UNHOOK")] Unhook = 2,
  }

  #endregion

}

#endregion Designer generated code
