// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HomeBlockArrangementInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from HomeBlockArrangementInfo.proto</summary>
  public static partial class HomeBlockArrangementInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for HomeBlockArrangementInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HomeBlockArrangementInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Ib21lQmxvY2tBcnJhbmdlbWVudEluZm8ucHJvdG8aFEhvbWVBbmltYWxE",
            "YXRhLnByb3RvGhlIb21lQmxvY2tEb3RQYXR0ZXJuLnByb3RvGhhIb21lQmxv",
            "Y2tGaWVsZERhdGEucHJvdG8aF0hvbWVGdXJuaXR1cmVEYXRhLnByb3RvGhxI",
            "b21lRnVybml0dXJlU3VpdGVEYXRhLnByb3RvGhFIb21lTnBjRGF0YS5wcm90",
            "bxoZVW5rMjcwMF9CSUVNQ0RMSUZPRC5wcm90bxoZVW5rMjcwMF9HT0hNTEFG",
            "TkJHRi5wcm90bxoWV2Vla2VuZERqaW5uSW5mby5wcm90byK/BAoYSG9tZUJs",
            "b2NrQXJyYW5nZW1lbnRJbmZvEhMKC2lzX3VubG9ja2VkGAEgASgIEhUKDWNv",
            "bWZvcnRfdmFsdWUYAiABKA0SKwoSZGVwbG95X2FuaW1hbF9saXN0GAQgAygL",
            "Mg8uSG9tZUFuaW1hbERhdGESMQoTVW5rMjcwMF9IR0lFQ0hJTE9KTBgFIAMo",
            "CzIULlVuazI3MDBfR09ITUxBRk5CR0YSMgoXd2Vla2VuZF9kamlubl9pbmZv",
            "X2xpc3QYDSADKAsyES5XZWVrZW5kRGppbm5JbmZvEjUKFGZ1cm5pdHVyZV9z",
            "dWl0ZV9saXN0GA8gAygLMhcuSG9tZUZ1cm5pdHVyZVN1aXRlRGF0YRInCgpm",
            "aWVsZF9saXN0GAMgAygLMhMuSG9tZUJsb2NrRmllbGREYXRhEiUKD2RlcGxv",
            "eV9ucGNfbGlzdBgLIAMoCzIMLkhvbWVOcGNEYXRhEi4KEGRvdF9wYXR0ZXJu",
            "X2xpc3QYByADKAsyFC5Ib21lQmxvY2tEb3RQYXR0ZXJuEjUKGXBlcnNpc3Rl",
            "bnRfZnVybml0dXJlX2xpc3QYCSADKAsyEi5Ib21lRnVybml0dXJlRGF0YRIw",
            "ChRkZXBsb3lfZnVybml1cmVfbGlzdBgMIAMoCzISLkhvbWVGdXJuaXR1cmVE",
            "YXRhEhAKCGJsb2NrX2lkGAYgASgNEjEKE1VuazI3MDBfS0pHTExFRUhCUEYY",
            "DiADKAsyFC5VbmsyNzAwX0JJRU1DRExJRk9EQiKqAh9XZWVkd2Fja2VyLlNo",
            "YXJlZC5OZXR3b3JrLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Shared.Network.Proto.HomeAnimalDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.HomeBlockDotPatternReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.HomeBlockFieldDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.HomeFurnitureDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.HomeNpcDataReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.Unk2700BIEMCDLIFODReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.Unk2700GOHMLAFNBGFReflection.Descriptor, global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.HomeBlockArrangementInfo), global::Weedwacker.Shared.Network.Proto.HomeBlockArrangementInfo.Parser, new[]{ "IsUnlocked", "ComfortValue", "DeployAnimalList", "Unk2700HGIECHILOJL", "WeekendDjinnInfoList", "FurnitureSuiteList", "FieldList", "DeployNpcList", "DotPatternList", "PersistentFurnitureList", "DeployFurniureList", "BlockId", "Unk2700KJGLLEEHBPF" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HomeBlockArrangementInfo : pb::IMessage<HomeBlockArrangementInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomeBlockArrangementInfo> _parser = new pb::MessageParser<HomeBlockArrangementInfo>(() => new HomeBlockArrangementInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomeBlockArrangementInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.HomeBlockArrangementInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeBlockArrangementInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeBlockArrangementInfo(HomeBlockArrangementInfo other) : this() {
      isUnlocked_ = other.isUnlocked_;
      comfortValue_ = other.comfortValue_;
      deployAnimalList_ = other.deployAnimalList_.Clone();
      unk2700HGIECHILOJL_ = other.unk2700HGIECHILOJL_.Clone();
      weekendDjinnInfoList_ = other.weekendDjinnInfoList_.Clone();
      furnitureSuiteList_ = other.furnitureSuiteList_.Clone();
      fieldList_ = other.fieldList_.Clone();
      deployNpcList_ = other.deployNpcList_.Clone();
      dotPatternList_ = other.dotPatternList_.Clone();
      persistentFurnitureList_ = other.persistentFurnitureList_.Clone();
      deployFurniureList_ = other.deployFurniureList_.Clone();
      blockId_ = other.blockId_;
      unk2700KJGLLEEHBPF_ = other.unk2700KJGLLEEHBPF_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeBlockArrangementInfo Clone() {
      return new HomeBlockArrangementInfo(this);
    }

    /// <summary>Field number for the "is_unlocked" field.</summary>
    public const int IsUnlockedFieldNumber = 1;
    private bool isUnlocked_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsUnlocked {
      get { return isUnlocked_; }
      set {
        isUnlocked_ = value;
      }
    }

    /// <summary>Field number for the "comfort_value" field.</summary>
    public const int ComfortValueFieldNumber = 2;
    private uint comfortValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ComfortValue {
      get { return comfortValue_; }
      set {
        comfortValue_ = value;
      }
    }

    /// <summary>Field number for the "deploy_animal_list" field.</summary>
    public const int DeployAnimalListFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeAnimalData> _repeated_deployAnimalList_codec
        = pb::FieldCodec.ForMessage(34, global::Weedwacker.Shared.Network.Proto.HomeAnimalData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeAnimalData> deployAnimalList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeAnimalData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeAnimalData> DeployAnimalList {
      get { return deployAnimalList_; }
    }

    /// <summary>Field number for the "Unk2700_HGIECHILOJL" field.</summary>
    public const int Unk2700HGIECHILOJLFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.Unk2700_GOHMLAFNBGF> _repeated_unk2700HGIECHILOJL_codec
        = pb::FieldCodec.ForMessage(42, global::Weedwacker.Shared.Network.Proto.Unk2700_GOHMLAFNBGF.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_GOHMLAFNBGF> unk2700HGIECHILOJL_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_GOHMLAFNBGF>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_GOHMLAFNBGF> Unk2700HGIECHILOJL {
      get { return unk2700HGIECHILOJL_; }
    }

    /// <summary>Field number for the "weekend_djinn_info_list" field.</summary>
    public const int WeekendDjinnInfoListFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfo> _repeated_weekendDjinnInfoList_codec
        = pb::FieldCodec.ForMessage(106, global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfo.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfo> weekendDjinnInfoList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.WeekendDjinnInfo> WeekendDjinnInfoList {
      get { return weekendDjinnInfoList_; }
    }

    /// <summary>Field number for the "furniture_suite_list" field.</summary>
    public const int FurnitureSuiteListFieldNumber = 15;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteData> _repeated_furnitureSuiteList_codec
        = pb::FieldCodec.ForMessage(122, global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteData> furnitureSuiteList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureSuiteData> FurnitureSuiteList {
      get { return furnitureSuiteList_; }
    }

    /// <summary>Field number for the "field_list" field.</summary>
    public const int FieldListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeBlockFieldData> _repeated_fieldList_codec
        = pb::FieldCodec.ForMessage(26, global::Weedwacker.Shared.Network.Proto.HomeBlockFieldData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockFieldData> fieldList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockFieldData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockFieldData> FieldList {
      get { return fieldList_; }
    }

    /// <summary>Field number for the "deploy_npc_list" field.</summary>
    public const int DeployNpcListFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeNpcData> _repeated_deployNpcList_codec
        = pb::FieldCodec.ForMessage(90, global::Weedwacker.Shared.Network.Proto.HomeNpcData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeNpcData> deployNpcList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeNpcData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeNpcData> DeployNpcList {
      get { return deployNpcList_; }
    }

    /// <summary>Field number for the "dot_pattern_list" field.</summary>
    public const int DotPatternListFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeBlockDotPattern> _repeated_dotPatternList_codec
        = pb::FieldCodec.ForMessage(58, global::Weedwacker.Shared.Network.Proto.HomeBlockDotPattern.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockDotPattern> dotPatternList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockDotPattern>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeBlockDotPattern> DotPatternList {
      get { return dotPatternList_; }
    }

    /// <summary>Field number for the "persistent_furniture_list" field.</summary>
    public const int PersistentFurnitureListFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> _repeated_persistentFurnitureList_codec
        = pb::FieldCodec.ForMessage(74, global::Weedwacker.Shared.Network.Proto.HomeFurnitureData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> persistentFurnitureList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> PersistentFurnitureList {
      get { return persistentFurnitureList_; }
    }

    /// <summary>Field number for the "deploy_furniure_list" field.</summary>
    public const int DeployFurniureListFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> _repeated_deployFurniureList_codec
        = pb::FieldCodec.ForMessage(98, global::Weedwacker.Shared.Network.Proto.HomeFurnitureData.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> deployFurniureList_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.HomeFurnitureData> DeployFurniureList {
      get { return deployFurniureList_; }
    }

    /// <summary>Field number for the "block_id" field.</summary>
    public const int BlockIdFieldNumber = 6;
    private uint blockId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BlockId {
      get { return blockId_; }
      set {
        blockId_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_KJGLLEEHBPF" field.</summary>
    public const int Unk2700KJGLLEEHBPFFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Weedwacker.Shared.Network.Proto.Unk2700_BIEMCDLIFOD> _repeated_unk2700KJGLLEEHBPF_codec
        = pb::FieldCodec.ForMessage(114, global::Weedwacker.Shared.Network.Proto.Unk2700_BIEMCDLIFOD.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_BIEMCDLIFOD> unk2700KJGLLEEHBPF_ = new pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_BIEMCDLIFOD>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Shared.Network.Proto.Unk2700_BIEMCDLIFOD> Unk2700KJGLLEEHBPF {
      get { return unk2700KJGLLEEHBPF_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomeBlockArrangementInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomeBlockArrangementInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsUnlocked != other.IsUnlocked) return false;
      if (ComfortValue != other.ComfortValue) return false;
      if(!deployAnimalList_.Equals(other.deployAnimalList_)) return false;
      if(!unk2700HGIECHILOJL_.Equals(other.unk2700HGIECHILOJL_)) return false;
      if(!weekendDjinnInfoList_.Equals(other.weekendDjinnInfoList_)) return false;
      if(!furnitureSuiteList_.Equals(other.furnitureSuiteList_)) return false;
      if(!fieldList_.Equals(other.fieldList_)) return false;
      if(!deployNpcList_.Equals(other.deployNpcList_)) return false;
      if(!dotPatternList_.Equals(other.dotPatternList_)) return false;
      if(!persistentFurnitureList_.Equals(other.persistentFurnitureList_)) return false;
      if(!deployFurniureList_.Equals(other.deployFurniureList_)) return false;
      if (BlockId != other.BlockId) return false;
      if(!unk2700KJGLLEEHBPF_.Equals(other.unk2700KJGLLEEHBPF_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsUnlocked != false) hash ^= IsUnlocked.GetHashCode();
      if (ComfortValue != 0) hash ^= ComfortValue.GetHashCode();
      hash ^= deployAnimalList_.GetHashCode();
      hash ^= unk2700HGIECHILOJL_.GetHashCode();
      hash ^= weekendDjinnInfoList_.GetHashCode();
      hash ^= furnitureSuiteList_.GetHashCode();
      hash ^= fieldList_.GetHashCode();
      hash ^= deployNpcList_.GetHashCode();
      hash ^= dotPatternList_.GetHashCode();
      hash ^= persistentFurnitureList_.GetHashCode();
      hash ^= deployFurniureList_.GetHashCode();
      if (BlockId != 0) hash ^= BlockId.GetHashCode();
      hash ^= unk2700KJGLLEEHBPF_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsUnlocked != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsUnlocked);
      }
      if (ComfortValue != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ComfortValue);
      }
      fieldList_.WriteTo(output, _repeated_fieldList_codec);
      deployAnimalList_.WriteTo(output, _repeated_deployAnimalList_codec);
      unk2700HGIECHILOJL_.WriteTo(output, _repeated_unk2700HGIECHILOJL_codec);
      if (BlockId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BlockId);
      }
      dotPatternList_.WriteTo(output, _repeated_dotPatternList_codec);
      persistentFurnitureList_.WriteTo(output, _repeated_persistentFurnitureList_codec);
      deployNpcList_.WriteTo(output, _repeated_deployNpcList_codec);
      deployFurniureList_.WriteTo(output, _repeated_deployFurniureList_codec);
      weekendDjinnInfoList_.WriteTo(output, _repeated_weekendDjinnInfoList_codec);
      unk2700KJGLLEEHBPF_.WriteTo(output, _repeated_unk2700KJGLLEEHBPF_codec);
      furnitureSuiteList_.WriteTo(output, _repeated_furnitureSuiteList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsUnlocked != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsUnlocked);
      }
      if (ComfortValue != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ComfortValue);
      }
      fieldList_.WriteTo(ref output, _repeated_fieldList_codec);
      deployAnimalList_.WriteTo(ref output, _repeated_deployAnimalList_codec);
      unk2700HGIECHILOJL_.WriteTo(ref output, _repeated_unk2700HGIECHILOJL_codec);
      if (BlockId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BlockId);
      }
      dotPatternList_.WriteTo(ref output, _repeated_dotPatternList_codec);
      persistentFurnitureList_.WriteTo(ref output, _repeated_persistentFurnitureList_codec);
      deployNpcList_.WriteTo(ref output, _repeated_deployNpcList_codec);
      deployFurniureList_.WriteTo(ref output, _repeated_deployFurniureList_codec);
      weekendDjinnInfoList_.WriteTo(ref output, _repeated_weekendDjinnInfoList_codec);
      unk2700KJGLLEEHBPF_.WriteTo(ref output, _repeated_unk2700KJGLLEEHBPF_codec);
      furnitureSuiteList_.WriteTo(ref output, _repeated_furnitureSuiteList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsUnlocked != false) {
        size += 1 + 1;
      }
      if (ComfortValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ComfortValue);
      }
      size += deployAnimalList_.CalculateSize(_repeated_deployAnimalList_codec);
      size += unk2700HGIECHILOJL_.CalculateSize(_repeated_unk2700HGIECHILOJL_codec);
      size += weekendDjinnInfoList_.CalculateSize(_repeated_weekendDjinnInfoList_codec);
      size += furnitureSuiteList_.CalculateSize(_repeated_furnitureSuiteList_codec);
      size += fieldList_.CalculateSize(_repeated_fieldList_codec);
      size += deployNpcList_.CalculateSize(_repeated_deployNpcList_codec);
      size += dotPatternList_.CalculateSize(_repeated_dotPatternList_codec);
      size += persistentFurnitureList_.CalculateSize(_repeated_persistentFurnitureList_codec);
      size += deployFurniureList_.CalculateSize(_repeated_deployFurniureList_codec);
      if (BlockId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BlockId);
      }
      size += unk2700KJGLLEEHBPF_.CalculateSize(_repeated_unk2700KJGLLEEHBPF_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomeBlockArrangementInfo other) {
      if (other == null) {
        return;
      }
      if (other.IsUnlocked != false) {
        IsUnlocked = other.IsUnlocked;
      }
      if (other.ComfortValue != 0) {
        ComfortValue = other.ComfortValue;
      }
      deployAnimalList_.Add(other.deployAnimalList_);
      unk2700HGIECHILOJL_.Add(other.unk2700HGIECHILOJL_);
      weekendDjinnInfoList_.Add(other.weekendDjinnInfoList_);
      furnitureSuiteList_.Add(other.furnitureSuiteList_);
      fieldList_.Add(other.fieldList_);
      deployNpcList_.Add(other.deployNpcList_);
      dotPatternList_.Add(other.dotPatternList_);
      persistentFurnitureList_.Add(other.persistentFurnitureList_);
      deployFurniureList_.Add(other.deployFurniureList_);
      if (other.BlockId != 0) {
        BlockId = other.BlockId;
      }
      unk2700KJGLLEEHBPF_.Add(other.unk2700KJGLLEEHBPF_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsUnlocked = input.ReadBool();
            break;
          }
          case 16: {
            ComfortValue = input.ReadUInt32();
            break;
          }
          case 26: {
            fieldList_.AddEntriesFrom(input, _repeated_fieldList_codec);
            break;
          }
          case 34: {
            deployAnimalList_.AddEntriesFrom(input, _repeated_deployAnimalList_codec);
            break;
          }
          case 42: {
            unk2700HGIECHILOJL_.AddEntriesFrom(input, _repeated_unk2700HGIECHILOJL_codec);
            break;
          }
          case 48: {
            BlockId = input.ReadUInt32();
            break;
          }
          case 58: {
            dotPatternList_.AddEntriesFrom(input, _repeated_dotPatternList_codec);
            break;
          }
          case 74: {
            persistentFurnitureList_.AddEntriesFrom(input, _repeated_persistentFurnitureList_codec);
            break;
          }
          case 90: {
            deployNpcList_.AddEntriesFrom(input, _repeated_deployNpcList_codec);
            break;
          }
          case 98: {
            deployFurniureList_.AddEntriesFrom(input, _repeated_deployFurniureList_codec);
            break;
          }
          case 106: {
            weekendDjinnInfoList_.AddEntriesFrom(input, _repeated_weekendDjinnInfoList_codec);
            break;
          }
          case 114: {
            unk2700KJGLLEEHBPF_.AddEntriesFrom(input, _repeated_unk2700KJGLLEEHBPF_codec);
            break;
          }
          case 122: {
            furnitureSuiteList_.AddEntriesFrom(input, _repeated_furnitureSuiteList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsUnlocked = input.ReadBool();
            break;
          }
          case 16: {
            ComfortValue = input.ReadUInt32();
            break;
          }
          case 26: {
            fieldList_.AddEntriesFrom(ref input, _repeated_fieldList_codec);
            break;
          }
          case 34: {
            deployAnimalList_.AddEntriesFrom(ref input, _repeated_deployAnimalList_codec);
            break;
          }
          case 42: {
            unk2700HGIECHILOJL_.AddEntriesFrom(ref input, _repeated_unk2700HGIECHILOJL_codec);
            break;
          }
          case 48: {
            BlockId = input.ReadUInt32();
            break;
          }
          case 58: {
            dotPatternList_.AddEntriesFrom(ref input, _repeated_dotPatternList_codec);
            break;
          }
          case 74: {
            persistentFurnitureList_.AddEntriesFrom(ref input, _repeated_persistentFurnitureList_codec);
            break;
          }
          case 90: {
            deployNpcList_.AddEntriesFrom(ref input, _repeated_deployNpcList_codec);
            break;
          }
          case 98: {
            deployFurniureList_.AddEntriesFrom(ref input, _repeated_deployFurniureList_codec);
            break;
          }
          case 106: {
            weekendDjinnInfoList_.AddEntriesFrom(ref input, _repeated_weekendDjinnInfoList_codec);
            break;
          }
          case 114: {
            unk2700KJGLLEEHBPF_.AddEntriesFrom(ref input, _repeated_unk2700KJGLLEEHBPF_codec);
            break;
          }
          case 122: {
            furnitureSuiteList_.AddEntriesFrom(ref input, _repeated_furnitureSuiteList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
