// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SkyCrystalDetectorQuickUseResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from SkyCrystalDetectorQuickUseResult.proto</summary>
  public static partial class SkyCrystalDetectorQuickUseResultReflection {

    #region Descriptor
    /// <summary>File descriptor for SkyCrystalDetectorQuickUseResult.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SkyCrystalDetectorQuickUseResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZTa3lDcnlzdGFsRGV0ZWN0b3JRdWlja1VzZVJlc3VsdC5wcm90bxoZVW5r",
            "MjcwMF9DQ0VPRU9ITEFQSy5wcm90byJmCiBTa3lDcnlzdGFsRGV0ZWN0b3JR",
            "dWlja1VzZVJlc3VsdBIxChNVbmsyNzAwX0NPSUVMSUdFQUNMGAkgASgLMhQu",
            "VW5rMjcwMF9DQ0VPRU9ITEFQSxIPCgdyZXRjb2RlGAggASgFQhqqAhdXZWVk",
            "d2Fja2VyLlNlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Server.Proto.Unk2700CCEOEOHLAPKReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.SkyCrystalDetectorQuickUseResult), global::Weedwacker.Server.Proto.SkyCrystalDetectorQuickUseResult.Parser, new[]{ "Unk2700COIELIGEACL", "Retcode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SkyCrystalDetectorQuickUseResult : pb::IMessage<SkyCrystalDetectorQuickUseResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkyCrystalDetectorQuickUseResult> _parser = new pb::MessageParser<SkyCrystalDetectorQuickUseResult>(() => new SkyCrystalDetectorQuickUseResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SkyCrystalDetectorQuickUseResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.SkyCrystalDetectorQuickUseResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkyCrystalDetectorQuickUseResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkyCrystalDetectorQuickUseResult(SkyCrystalDetectorQuickUseResult other) : this() {
      unk2700COIELIGEACL_ = other.unk2700COIELIGEACL_ != null ? other.unk2700COIELIGEACL_.Clone() : null;
      retcode_ = other.retcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SkyCrystalDetectorQuickUseResult Clone() {
      return new SkyCrystalDetectorQuickUseResult(this);
    }

    /// <summary>Field number for the "Unk2700_COIELIGEACL" field.</summary>
    public const int Unk2700COIELIGEACLFieldNumber = 9;
    private global::Weedwacker.Server.Proto.Unk2700_CCEOEOHLAPK unk2700COIELIGEACL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Unk2700_CCEOEOHLAPK Unk2700COIELIGEACL {
      get { return unk2700COIELIGEACL_; }
      set {
        unk2700COIELIGEACL_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 8;
    private int retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SkyCrystalDetectorQuickUseResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SkyCrystalDetectorQuickUseResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Unk2700COIELIGEACL, other.Unk2700COIELIGEACL)) return false;
      if (Retcode != other.Retcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (unk2700COIELIGEACL_ != null) hash ^= Unk2700COIELIGEACL.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Retcode != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Retcode);
      }
      if (unk2700COIELIGEACL_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Unk2700COIELIGEACL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Retcode != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Retcode);
      }
      if (unk2700COIELIGEACL_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Unk2700COIELIGEACL);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (unk2700COIELIGEACL_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unk2700COIELIGEACL);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SkyCrystalDetectorQuickUseResult other) {
      if (other == null) {
        return;
      }
      if (other.unk2700COIELIGEACL_ != null) {
        if (unk2700COIELIGEACL_ == null) {
          Unk2700COIELIGEACL = new global::Weedwacker.Server.Proto.Unk2700_CCEOEOHLAPK();
        }
        Unk2700COIELIGEACL.MergeFrom(other.Unk2700COIELIGEACL);
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 64: {
            Retcode = input.ReadInt32();
            break;
          }
          case 74: {
            if (unk2700COIELIGEACL_ == null) {
              Unk2700COIELIGEACL = new global::Weedwacker.Server.Proto.Unk2700_CCEOEOHLAPK();
            }
            input.ReadMessage(Unk2700COIELIGEACL);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 64: {
            Retcode = input.ReadInt32();
            break;
          }
          case 74: {
            if (unk2700COIELIGEACL_ == null) {
              Unk2700COIELIGEACL = new global::Weedwacker.Server.Proto.Unk2700_CCEOEOHLAPK();
            }
            input.ReadMessage(Unk2700COIELIGEACL);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
