// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Unk2700_OGKIDNPMMKG.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from Unk2700_OGKIDNPMMKG.proto</summary>
  public static partial class Unk2700OGKIDNPMMKGReflection {

    #region Descriptor
    /// <summary>File descriptor for Unk2700_OGKIDNPMMKG.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Unk2700OGKIDNPMMKGReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVbmsyNzAwX09HS0lETlBNTUtHLnByb3RvGhlVbmsyNzAwX0hHTUNOSk9Q",
            "REFBLnByb3RvInoKE1VuazI3MDBfT0dLSUROUE1NS0cSMQoTVW5rMjcwMF9N",
            "SU5FSEtBR09HQRgLIAEoDjIULlVuazI3MDBfSEdNQ05KT1BEQUESEwoLZXhw",
            "aXJlX3RpbWUYBiABKA0SGwoTVW5rMjcwMF9PTk9PSkJFQUJPRRgFIAEoBEIa",
            "qgIXV2VlZHdhY2tlci5TZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Server.Proto.Unk2700HGMCNJOPDAAReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.Unk2700_OGKIDNPMMKG), global::Weedwacker.Server.Proto.Unk2700_OGKIDNPMMKG.Parser, new[]{ "Unk2700MINEHKAGOGA", "ExpireTime", "Unk2700ONOOJBEABOE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Unk2700_OGKIDNPMMKG : pb::IMessage<Unk2700_OGKIDNPMMKG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Unk2700_OGKIDNPMMKG> _parser = new pb::MessageParser<Unk2700_OGKIDNPMMKG>(() => new Unk2700_OGKIDNPMMKG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Unk2700_OGKIDNPMMKG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.Unk2700OGKIDNPMMKGReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_OGKIDNPMMKG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_OGKIDNPMMKG(Unk2700_OGKIDNPMMKG other) : this() {
      unk2700MINEHKAGOGA_ = other.unk2700MINEHKAGOGA_;
      expireTime_ = other.expireTime_;
      unk2700ONOOJBEABOE_ = other.unk2700ONOOJBEABOE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_OGKIDNPMMKG Clone() {
      return new Unk2700_OGKIDNPMMKG(this);
    }

    /// <summary>Field number for the "Unk2700_MINEHKAGOGA" field.</summary>
    public const int Unk2700MINEHKAGOGAFieldNumber = 11;
    private global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA unk2700MINEHKAGOGA_ = global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA Unk2700MINEHKAGOGA {
      get { return unk2700MINEHKAGOGA_; }
      set {
        unk2700MINEHKAGOGA_ = value;
      }
    }

    /// <summary>Field number for the "expire_time" field.</summary>
    public const int ExpireTimeFieldNumber = 6;
    private uint expireTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ExpireTime {
      get { return expireTime_; }
      set {
        expireTime_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_ONOOJBEABOE" field.</summary>
    public const int Unk2700ONOOJBEABOEFieldNumber = 5;
    private ulong unk2700ONOOJBEABOE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Unk2700ONOOJBEABOE {
      get { return unk2700ONOOJBEABOE_; }
      set {
        unk2700ONOOJBEABOE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Unk2700_OGKIDNPMMKG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Unk2700_OGKIDNPMMKG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unk2700MINEHKAGOGA != other.Unk2700MINEHKAGOGA) return false;
      if (ExpireTime != other.ExpireTime) return false;
      if (Unk2700ONOOJBEABOE != other.Unk2700ONOOJBEABOE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk2700MINEHKAGOGA != global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None) hash ^= Unk2700MINEHKAGOGA.GetHashCode();
      if (ExpireTime != 0) hash ^= ExpireTime.GetHashCode();
      if (Unk2700ONOOJBEABOE != 0UL) hash ^= Unk2700ONOOJBEABOE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk2700ONOOJBEABOE != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Unk2700ONOOJBEABOE);
      }
      if (ExpireTime != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ExpireTime);
      }
      if (Unk2700MINEHKAGOGA != global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Unk2700MINEHKAGOGA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk2700ONOOJBEABOE != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Unk2700ONOOJBEABOE);
      }
      if (ExpireTime != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ExpireTime);
      }
      if (Unk2700MINEHKAGOGA != global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Unk2700MINEHKAGOGA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk2700MINEHKAGOGA != global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Unk2700MINEHKAGOGA);
      }
      if (ExpireTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ExpireTime);
      }
      if (Unk2700ONOOJBEABOE != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Unk2700ONOOJBEABOE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Unk2700_OGKIDNPMMKG other) {
      if (other == null) {
        return;
      }
      if (other.Unk2700MINEHKAGOGA != global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA.None) {
        Unk2700MINEHKAGOGA = other.Unk2700MINEHKAGOGA;
      }
      if (other.ExpireTime != 0) {
        ExpireTime = other.ExpireTime;
      }
      if (other.Unk2700ONOOJBEABOE != 0UL) {
        Unk2700ONOOJBEABOE = other.Unk2700ONOOJBEABOE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 40: {
            Unk2700ONOOJBEABOE = input.ReadUInt64();
            break;
          }
          case 48: {
            ExpireTime = input.ReadUInt32();
            break;
          }
          case 88: {
            Unk2700MINEHKAGOGA = (global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 40: {
            Unk2700ONOOJBEABOE = input.ReadUInt64();
            break;
          }
          case 48: {
            ExpireTime = input.ReadUInt32();
            break;
          }
          case 88: {
            Unk2700MINEHKAGOGA = (global::Weedwacker.Server.Proto.Unk2700_HGMCNJOPDAA) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
