// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Unk3000_GDDGGJIFNCH.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from Unk3000_GDDGGJIFNCH.proto</summary>
  public static partial class Unk3000GDDGGJIFNCHReflection {

    #region Descriptor
    /// <summary>File descriptor for Unk3000_GDDGGJIFNCH.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Unk3000GDDGGJIFNCHReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVbmszMDAwX0dEREdHSklGTkNILnByb3RvIqYBChNVbmszMDAwX0dEREdH",
            "SklGTkNIEhsKE1VuazMwMDBfQ0ZETUxHS05MS0wYCCABKA0SGwoTVW5rMzAw",
            "MF9IT05JTkRFSExOTxgPIAEoCBIbChNVbmszMDAwX0ZJTUVOQUxDQUtHGAog",
            "ASgIEhsKE1VuazMwMDBfQkpHTktERUdMR0MYBiABKAgSGwoTVW5rMzAwMF9I",
            "UEhMR0ZESEJPThgFIAEoDUIaqgIXV2VlZHdhY2tlci5TZXJ2ZXIuUHJvdG9i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.Unk3000_GDDGGJIFNCH), global::Weedwacker.Server.Proto.Unk3000_GDDGGJIFNCH.Parser, new[]{ "Unk3000CFDMLGKNLKL", "Unk3000HONINDEHLNO", "Unk3000FIMENALCAKG", "Unk3000BJGNKDEGLGC", "Unk3000HPHLGFDHBON" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Unk3000_GDDGGJIFNCH : pb::IMessage<Unk3000_GDDGGJIFNCH>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Unk3000_GDDGGJIFNCH> _parser = new pb::MessageParser<Unk3000_GDDGGJIFNCH>(() => new Unk3000_GDDGGJIFNCH());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Unk3000_GDDGGJIFNCH> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.Unk3000GDDGGJIFNCHReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_GDDGGJIFNCH() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_GDDGGJIFNCH(Unk3000_GDDGGJIFNCH other) : this() {
      unk3000CFDMLGKNLKL_ = other.unk3000CFDMLGKNLKL_;
      unk3000HONINDEHLNO_ = other.unk3000HONINDEHLNO_;
      unk3000FIMENALCAKG_ = other.unk3000FIMENALCAKG_;
      unk3000BJGNKDEGLGC_ = other.unk3000BJGNKDEGLGC_;
      unk3000HPHLGFDHBON_ = other.unk3000HPHLGFDHBON_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_GDDGGJIFNCH Clone() {
      return new Unk3000_GDDGGJIFNCH(this);
    }

    /// <summary>Field number for the "Unk3000_CFDMLGKNLKL" field.</summary>
    public const int Unk3000CFDMLGKNLKLFieldNumber = 8;
    private uint unk3000CFDMLGKNLKL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3000CFDMLGKNLKL {
      get { return unk3000CFDMLGKNLKL_; }
      set {
        unk3000CFDMLGKNLKL_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_HONINDEHLNO" field.</summary>
    public const int Unk3000HONINDEHLNOFieldNumber = 15;
    private bool unk3000HONINDEHLNO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000HONINDEHLNO {
      get { return unk3000HONINDEHLNO_; }
      set {
        unk3000HONINDEHLNO_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_FIMENALCAKG" field.</summary>
    public const int Unk3000FIMENALCAKGFieldNumber = 10;
    private bool unk3000FIMENALCAKG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000FIMENALCAKG {
      get { return unk3000FIMENALCAKG_; }
      set {
        unk3000FIMENALCAKG_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_BJGNKDEGLGC" field.</summary>
    public const int Unk3000BJGNKDEGLGCFieldNumber = 6;
    private bool unk3000BJGNKDEGLGC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000BJGNKDEGLGC {
      get { return unk3000BJGNKDEGLGC_; }
      set {
        unk3000BJGNKDEGLGC_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_HPHLGFDHBON" field.</summary>
    public const int Unk3000HPHLGFDHBONFieldNumber = 5;
    private uint unk3000HPHLGFDHBON_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3000HPHLGFDHBON {
      get { return unk3000HPHLGFDHBON_; }
      set {
        unk3000HPHLGFDHBON_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Unk3000_GDDGGJIFNCH);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Unk3000_GDDGGJIFNCH other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unk3000CFDMLGKNLKL != other.Unk3000CFDMLGKNLKL) return false;
      if (Unk3000HONINDEHLNO != other.Unk3000HONINDEHLNO) return false;
      if (Unk3000FIMENALCAKG != other.Unk3000FIMENALCAKG) return false;
      if (Unk3000BJGNKDEGLGC != other.Unk3000BJGNKDEGLGC) return false;
      if (Unk3000HPHLGFDHBON != other.Unk3000HPHLGFDHBON) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk3000CFDMLGKNLKL != 0) hash ^= Unk3000CFDMLGKNLKL.GetHashCode();
      if (Unk3000HONINDEHLNO != false) hash ^= Unk3000HONINDEHLNO.GetHashCode();
      if (Unk3000FIMENALCAKG != false) hash ^= Unk3000FIMENALCAKG.GetHashCode();
      if (Unk3000BJGNKDEGLGC != false) hash ^= Unk3000BJGNKDEGLGC.GetHashCode();
      if (Unk3000HPHLGFDHBON != 0) hash ^= Unk3000HPHLGFDHBON.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk3000HPHLGFDHBON != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Unk3000HPHLGFDHBON);
      }
      if (Unk3000BJGNKDEGLGC != false) {
        output.WriteRawTag(48);
        output.WriteBool(Unk3000BJGNKDEGLGC);
      }
      if (Unk3000CFDMLGKNLKL != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Unk3000CFDMLGKNLKL);
      }
      if (Unk3000FIMENALCAKG != false) {
        output.WriteRawTag(80);
        output.WriteBool(Unk3000FIMENALCAKG);
      }
      if (Unk3000HONINDEHLNO != false) {
        output.WriteRawTag(120);
        output.WriteBool(Unk3000HONINDEHLNO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk3000HPHLGFDHBON != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Unk3000HPHLGFDHBON);
      }
      if (Unk3000BJGNKDEGLGC != false) {
        output.WriteRawTag(48);
        output.WriteBool(Unk3000BJGNKDEGLGC);
      }
      if (Unk3000CFDMLGKNLKL != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Unk3000CFDMLGKNLKL);
      }
      if (Unk3000FIMENALCAKG != false) {
        output.WriteRawTag(80);
        output.WriteBool(Unk3000FIMENALCAKG);
      }
      if (Unk3000HONINDEHLNO != false) {
        output.WriteRawTag(120);
        output.WriteBool(Unk3000HONINDEHLNO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk3000CFDMLGKNLKL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3000CFDMLGKNLKL);
      }
      if (Unk3000HONINDEHLNO != false) {
        size += 1 + 1;
      }
      if (Unk3000FIMENALCAKG != false) {
        size += 1 + 1;
      }
      if (Unk3000BJGNKDEGLGC != false) {
        size += 1 + 1;
      }
      if (Unk3000HPHLGFDHBON != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk3000HPHLGFDHBON);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Unk3000_GDDGGJIFNCH other) {
      if (other == null) {
        return;
      }
      if (other.Unk3000CFDMLGKNLKL != 0) {
        Unk3000CFDMLGKNLKL = other.Unk3000CFDMLGKNLKL;
      }
      if (other.Unk3000HONINDEHLNO != false) {
        Unk3000HONINDEHLNO = other.Unk3000HONINDEHLNO;
      }
      if (other.Unk3000FIMENALCAKG != false) {
        Unk3000FIMENALCAKG = other.Unk3000FIMENALCAKG;
      }
      if (other.Unk3000BJGNKDEGLGC != false) {
        Unk3000BJGNKDEGLGC = other.Unk3000BJGNKDEGLGC;
      }
      if (other.Unk3000HPHLGFDHBON != 0) {
        Unk3000HPHLGFDHBON = other.Unk3000HPHLGFDHBON;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 40: {
            Unk3000HPHLGFDHBON = input.ReadUInt32();
            break;
          }
          case 48: {
            Unk3000BJGNKDEGLGC = input.ReadBool();
            break;
          }
          case 64: {
            Unk3000CFDMLGKNLKL = input.ReadUInt32();
            break;
          }
          case 80: {
            Unk3000FIMENALCAKG = input.ReadBool();
            break;
          }
          case 120: {
            Unk3000HONINDEHLNO = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 40: {
            Unk3000HPHLGFDHBON = input.ReadUInt32();
            break;
          }
          case 48: {
            Unk3000BJGNKDEGLGC = input.ReadBool();
            break;
          }
          case 64: {
            Unk3000CFDMLGKNLKL = input.ReadUInt32();
            break;
          }
          case 80: {
            Unk3000FIMENALCAKG = input.ReadBool();
            break;
          }
          case 120: {
            Unk3000HONINDEHLNO = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
