// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Unk3000_HPFGNOIGNAG.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Shared.Network.Proto {

  /// <summary>Holder for reflection information generated from Unk3000_HPFGNOIGNAG.proto</summary>
  public static partial class Unk3000HPFGNOIGNAGReflection {

    #region Descriptor
    /// <summary>File descriptor for Unk3000_HPFGNOIGNAG.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Unk3000HPFGNOIGNAGReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVbmszMDAwX0hQRkdOT0lHTkFHLnByb3RvIoIBChNVbmszMDAwX0hQRkdO",
            "T0lHTkFHEhsKE1VuazMwMDBfUEhJSUJDTU5QRUsYCyABKAgSGwoTVW5rMzAw",
            "MF9ORkxFSU5BQlBQQxgHIAEoCBINCgVyb3VuZBgPIAEoDRIQCghzdGFnZV9p",
            "ZBgIIAEoDRIQCghsZXZlbF9pZBgKIAEoDUIiqgIfV2VlZHdhY2tlci5TaGFy",
            "ZWQuTmV0d29yay5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Shared.Network.Proto.Unk3000_HPFGNOIGNAG), global::Weedwacker.Shared.Network.Proto.Unk3000_HPFGNOIGNAG.Parser, new[]{ "Unk3000PHIIBCMNPEK", "Unk3000NFLEINABPPC", "Round", "StageId", "LevelId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 21961
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// </summary>
  public sealed partial class Unk3000_HPFGNOIGNAG : pb::IMessage<Unk3000_HPFGNOIGNAG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Unk3000_HPFGNOIGNAG> _parser = new pb::MessageParser<Unk3000_HPFGNOIGNAG>(() => new Unk3000_HPFGNOIGNAG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Unk3000_HPFGNOIGNAG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Shared.Network.Proto.Unk3000HPFGNOIGNAGReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_HPFGNOIGNAG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_HPFGNOIGNAG(Unk3000_HPFGNOIGNAG other) : this() {
      unk3000PHIIBCMNPEK_ = other.unk3000PHIIBCMNPEK_;
      unk3000NFLEINABPPC_ = other.unk3000NFLEINABPPC_;
      round_ = other.round_;
      stageId_ = other.stageId_;
      levelId_ = other.levelId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk3000_HPFGNOIGNAG Clone() {
      return new Unk3000_HPFGNOIGNAG(this);
    }

    /// <summary>Field number for the "Unk3000_PHIIBCMNPEK" field.</summary>
    public const int Unk3000PHIIBCMNPEKFieldNumber = 11;
    private bool unk3000PHIIBCMNPEK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000PHIIBCMNPEK {
      get { return unk3000PHIIBCMNPEK_; }
      set {
        unk3000PHIIBCMNPEK_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_NFLEINABPPC" field.</summary>
    public const int Unk3000NFLEINABPPCFieldNumber = 7;
    private bool unk3000NFLEINABPPC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000NFLEINABPPC {
      get { return unk3000NFLEINABPPC_; }
      set {
        unk3000NFLEINABPPC_ = value;
      }
    }

    /// <summary>Field number for the "round" field.</summary>
    public const int RoundFieldNumber = 15;
    private uint round_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Round {
      get { return round_; }
      set {
        round_ = value;
      }
    }

    /// <summary>Field number for the "stage_id" field.</summary>
    public const int StageIdFieldNumber = 8;
    private uint stageId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StageId {
      get { return stageId_; }
      set {
        stageId_ = value;
      }
    }

    /// <summary>Field number for the "level_id" field.</summary>
    public const int LevelIdFieldNumber = 10;
    private uint levelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LevelId {
      get { return levelId_; }
      set {
        levelId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Unk3000_HPFGNOIGNAG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Unk3000_HPFGNOIGNAG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unk3000PHIIBCMNPEK != other.Unk3000PHIIBCMNPEK) return false;
      if (Unk3000NFLEINABPPC != other.Unk3000NFLEINABPPC) return false;
      if (Round != other.Round) return false;
      if (StageId != other.StageId) return false;
      if (LevelId != other.LevelId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk3000PHIIBCMNPEK != false) hash ^= Unk3000PHIIBCMNPEK.GetHashCode();
      if (Unk3000NFLEINABPPC != false) hash ^= Unk3000NFLEINABPPC.GetHashCode();
      if (Round != 0) hash ^= Round.GetHashCode();
      if (StageId != 0) hash ^= StageId.GetHashCode();
      if (LevelId != 0) hash ^= LevelId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk3000NFLEINABPPC != false) {
        output.WriteRawTag(56);
        output.WriteBool(Unk3000NFLEINABPPC);
      }
      if (StageId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(StageId);
      }
      if (LevelId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LevelId);
      }
      if (Unk3000PHIIBCMNPEK != false) {
        output.WriteRawTag(88);
        output.WriteBool(Unk3000PHIIBCMNPEK);
      }
      if (Round != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Round);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk3000NFLEINABPPC != false) {
        output.WriteRawTag(56);
        output.WriteBool(Unk3000NFLEINABPPC);
      }
      if (StageId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(StageId);
      }
      if (LevelId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LevelId);
      }
      if (Unk3000PHIIBCMNPEK != false) {
        output.WriteRawTag(88);
        output.WriteBool(Unk3000PHIIBCMNPEK);
      }
      if (Round != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Round);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk3000PHIIBCMNPEK != false) {
        size += 1 + 1;
      }
      if (Unk3000NFLEINABPPC != false) {
        size += 1 + 1;
      }
      if (Round != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Round);
      }
      if (StageId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StageId);
      }
      if (LevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LevelId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Unk3000_HPFGNOIGNAG other) {
      if (other == null) {
        return;
      }
      if (other.Unk3000PHIIBCMNPEK != false) {
        Unk3000PHIIBCMNPEK = other.Unk3000PHIIBCMNPEK;
      }
      if (other.Unk3000NFLEINABPPC != false) {
        Unk3000NFLEINABPPC = other.Unk3000NFLEINABPPC;
      }
      if (other.Round != 0) {
        Round = other.Round;
      }
      if (other.StageId != 0) {
        StageId = other.StageId;
      }
      if (other.LevelId != 0) {
        LevelId = other.LevelId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 56: {
            Unk3000NFLEINABPPC = input.ReadBool();
            break;
          }
          case 64: {
            StageId = input.ReadUInt32();
            break;
          }
          case 80: {
            LevelId = input.ReadUInt32();
            break;
          }
          case 88: {
            Unk3000PHIIBCMNPEK = input.ReadBool();
            break;
          }
          case 120: {
            Round = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 56: {
            Unk3000NFLEINABPPC = input.ReadBool();
            break;
          }
          case 64: {
            StageId = input.ReadUInt32();
            break;
          }
          case 80: {
            LevelId = input.ReadUInt32();
            break;
          }
          case 88: {
            Unk3000PHIIBCMNPEK = input.ReadBool();
            break;
          }
          case 120: {
            Round = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
