// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BeginCameraSceneLookNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from BeginCameraSceneLookNotify.proto</summary>
  public static partial class BeginCameraSceneLookNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for BeginCameraSceneLookNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeginCameraSceneLookNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBCZWdpbkNhbWVyYVNjZW5lTG9va05vdGlmeS5wcm90bxoMVmVjdG9yLnBy",
            "b3RvIrwFChpCZWdpbkNhbWVyYVNjZW5lTG9va05vdGlmeRIcChNVbmszMDAw",
            "X01OTExDSk1QTU5IGIIJIAEoDRIbChNVbmsyNzAwX0RIQUhFS09HSEJKGAcg",
            "ASgCEhgKEGlzX3NldF9zY3JlZW5feHkYBSABKAgSGQoIbG9va19wb3MYBCAB",
            "KAsyBy5WZWN0b3ISHwoXaXNfcmVjb3Zlcl9rZWVwX2N1cnJlbnQYCyABKAgS",
            "HAoTVW5rMzAwMF9HT1BJRlBNRkVQQhjfCiABKAgSTAoTVW5rMjcwMF9ISUFL",
            "Tk5DS0hKQhgGIAEoDjIvLkJlZ2luQ2FtZXJhU2NlbmVMb29rTm90aWZ5LlVu",
            "azI3MDBfTE5DSERET09FQ0QSGwoTaXNfY2hhbmdlX3BsYXlfbW9kZRgJIAEo",
            "CBIcChNVbmszMDAwX0lFRklLTUhDS0RIGM8IIAEoDRIQCghzY3JlZW5feRgP",
            "IAEoAhIZChFpc19zZXRfZm9sbG93X3BvcxgNIAEoCBIQCghpc19mb3JjZRgM",
            "IAEoCBIcChNVbmszMDAwX09HQ0xNRkZBREJEGN4NIAEoAhISCgllbnRpdHlf",
            "aWQYrwogASgNEhAKCHNjcmVlbl94GAMgASgCEhUKDWlzX2ZvcmNlX3dhbGsY",
            "CiABKAgSFAoMb3RoZXJfcGFyYW1zGAEgAygJEhsKCmZvbGxvd19wb3MYCCAB",
            "KAsyBy5WZWN0b3ISFgoOaXNfYWxsb3dfaW5wdXQYAiABKAgSEAoIZHVyYXRp",
            "b24YDiABKAIibwoTVW5rMjcwMF9MTkNIRERPT0VDRBIrCidVbmsyNzAwX0xO",
            "Q0hERE9PRUNEX1VuazI3MDBfQUNPRU5CTURGQlAQABIrCidVbmsyNzAwX0xO",
            "Q0hERE9PRUNEX1VuazI3MDBfRktCTENERkxDT00QAUIaqgIXV2VlZHdhY2tl",
            "ci5TZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Server.Proto.VectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify), global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Parser, new[]{ "Unk3000MNLLCJMPMNH", "Unk2700DHAHEKOGHBJ", "IsSetScreenXy", "LookPos", "IsRecoverKeepCurrent", "Unk3000GOPIFPMFEPB", "Unk2700HIAKNNCKHJB", "IsChangePlayMode", "Unk3000IEFIKMHCKDH", "ScreenY", "IsSetFollowPos", "IsForce", "Unk3000OGCLMFFADBD", "EntityId", "ScreenX", "IsForceWalk", "OtherParams", "FollowPos", "IsAllowInput", "Duration" }, null, new[]{ typeof(global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 270
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// </summary>
  public sealed partial class BeginCameraSceneLookNotify : pb::IMessage<BeginCameraSceneLookNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BeginCameraSceneLookNotify> _parser = new pb::MessageParser<BeginCameraSceneLookNotify>(() => new BeginCameraSceneLookNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BeginCameraSceneLookNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.BeginCameraSceneLookNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginCameraSceneLookNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginCameraSceneLookNotify(BeginCameraSceneLookNotify other) : this() {
      unk3000MNLLCJMPMNH_ = other.unk3000MNLLCJMPMNH_;
      unk2700DHAHEKOGHBJ_ = other.unk2700DHAHEKOGHBJ_;
      isSetScreenXy_ = other.isSetScreenXy_;
      lookPos_ = other.lookPos_ != null ? other.lookPos_.Clone() : null;
      isRecoverKeepCurrent_ = other.isRecoverKeepCurrent_;
      unk3000GOPIFPMFEPB_ = other.unk3000GOPIFPMFEPB_;
      unk2700HIAKNNCKHJB_ = other.unk2700HIAKNNCKHJB_;
      isChangePlayMode_ = other.isChangePlayMode_;
      unk3000IEFIKMHCKDH_ = other.unk3000IEFIKMHCKDH_;
      screenY_ = other.screenY_;
      isSetFollowPos_ = other.isSetFollowPos_;
      isForce_ = other.isForce_;
      unk3000OGCLMFFADBD_ = other.unk3000OGCLMFFADBD_;
      entityId_ = other.entityId_;
      screenX_ = other.screenX_;
      isForceWalk_ = other.isForceWalk_;
      otherParams_ = other.otherParams_.Clone();
      followPos_ = other.followPos_ != null ? other.followPos_.Clone() : null;
      isAllowInput_ = other.isAllowInput_;
      duration_ = other.duration_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginCameraSceneLookNotify Clone() {
      return new BeginCameraSceneLookNotify(this);
    }

    /// <summary>Field number for the "Unk3000_MNLLCJMPMNH" field.</summary>
    public const int Unk3000MNLLCJMPMNHFieldNumber = 1154;
    private uint unk3000MNLLCJMPMNH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3000MNLLCJMPMNH {
      get { return unk3000MNLLCJMPMNH_; }
      set {
        unk3000MNLLCJMPMNH_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_DHAHEKOGHBJ" field.</summary>
    public const int Unk2700DHAHEKOGHBJFieldNumber = 7;
    private float unk2700DHAHEKOGHBJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk2700DHAHEKOGHBJ {
      get { return unk2700DHAHEKOGHBJ_; }
      set {
        unk2700DHAHEKOGHBJ_ = value;
      }
    }

    /// <summary>Field number for the "is_set_screen_xy" field.</summary>
    public const int IsSetScreenXyFieldNumber = 5;
    private bool isSetScreenXy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSetScreenXy {
      get { return isSetScreenXy_; }
      set {
        isSetScreenXy_ = value;
      }
    }

    /// <summary>Field number for the "look_pos" field.</summary>
    public const int LookPosFieldNumber = 4;
    private global::Weedwacker.Server.Proto.Vector lookPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Vector LookPos {
      get { return lookPos_; }
      set {
        lookPos_ = value;
      }
    }

    /// <summary>Field number for the "is_recover_keep_current" field.</summary>
    public const int IsRecoverKeepCurrentFieldNumber = 11;
    private bool isRecoverKeepCurrent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRecoverKeepCurrent {
      get { return isRecoverKeepCurrent_; }
      set {
        isRecoverKeepCurrent_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_GOPIFPMFEPB" field.</summary>
    public const int Unk3000GOPIFPMFEPBFieldNumber = 1375;
    private bool unk3000GOPIFPMFEPB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3000GOPIFPMFEPB {
      get { return unk3000GOPIFPMFEPB_; }
      set {
        unk3000GOPIFPMFEPB_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_HIAKNNCKHJB" field.</summary>
    public const int Unk2700HIAKNNCKHJBFieldNumber = 6;
    private global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD unk2700HIAKNNCKHJB_ = global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD Unk2700HIAKNNCKHJB {
      get { return unk2700HIAKNNCKHJB_; }
      set {
        unk2700HIAKNNCKHJB_ = value;
      }
    }

    /// <summary>Field number for the "is_change_play_mode" field.</summary>
    public const int IsChangePlayModeFieldNumber = 9;
    private bool isChangePlayMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsChangePlayMode {
      get { return isChangePlayMode_; }
      set {
        isChangePlayMode_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_IEFIKMHCKDH" field.</summary>
    public const int Unk3000IEFIKMHCKDHFieldNumber = 1103;
    private uint unk3000IEFIKMHCKDH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk3000IEFIKMHCKDH {
      get { return unk3000IEFIKMHCKDH_; }
      set {
        unk3000IEFIKMHCKDH_ = value;
      }
    }

    /// <summary>Field number for the "screen_y" field.</summary>
    public const int ScreenYFieldNumber = 15;
    private float screenY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ScreenY {
      get { return screenY_; }
      set {
        screenY_ = value;
      }
    }

    /// <summary>Field number for the "is_set_follow_pos" field.</summary>
    public const int IsSetFollowPosFieldNumber = 13;
    private bool isSetFollowPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSetFollowPos {
      get { return isSetFollowPos_; }
      set {
        isSetFollowPos_ = value;
      }
    }

    /// <summary>Field number for the "is_force" field.</summary>
    public const int IsForceFieldNumber = 12;
    private bool isForce_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsForce {
      get { return isForce_; }
      set {
        isForce_ = value;
      }
    }

    /// <summary>Field number for the "Unk3000_OGCLMFFADBD" field.</summary>
    public const int Unk3000OGCLMFFADBDFieldNumber = 1758;
    private float unk3000OGCLMFFADBD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Unk3000OGCLMFFADBD {
      get { return unk3000OGCLMFFADBD_; }
      set {
        unk3000OGCLMFFADBD_ = value;
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1327;
    private uint entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "screen_x" field.</summary>
    public const int ScreenXFieldNumber = 3;
    private float screenX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ScreenX {
      get { return screenX_; }
      set {
        screenX_ = value;
      }
    }

    /// <summary>Field number for the "is_force_walk" field.</summary>
    public const int IsForceWalkFieldNumber = 10;
    private bool isForceWalk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsForceWalk {
      get { return isForceWalk_; }
      set {
        isForceWalk_ = value;
      }
    }

    /// <summary>Field number for the "other_params" field.</summary>
    public const int OtherParamsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_otherParams_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> otherParams_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> OtherParams {
      get { return otherParams_; }
    }

    /// <summary>Field number for the "follow_pos" field.</summary>
    public const int FollowPosFieldNumber = 8;
    private global::Weedwacker.Server.Proto.Vector followPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Vector FollowPos {
      get { return followPos_; }
      set {
        followPos_ = value;
      }
    }

    /// <summary>Field number for the "is_allow_input" field.</summary>
    public const int IsAllowInputFieldNumber = 2;
    private bool isAllowInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAllowInput {
      get { return isAllowInput_; }
      set {
        isAllowInput_ = value;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 14;
    private float duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BeginCameraSceneLookNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BeginCameraSceneLookNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unk3000MNLLCJMPMNH != other.Unk3000MNLLCJMPMNH) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk2700DHAHEKOGHBJ, other.Unk2700DHAHEKOGHBJ)) return false;
      if (IsSetScreenXy != other.IsSetScreenXy) return false;
      if (!object.Equals(LookPos, other.LookPos)) return false;
      if (IsRecoverKeepCurrent != other.IsRecoverKeepCurrent) return false;
      if (Unk3000GOPIFPMFEPB != other.Unk3000GOPIFPMFEPB) return false;
      if (Unk2700HIAKNNCKHJB != other.Unk2700HIAKNNCKHJB) return false;
      if (IsChangePlayMode != other.IsChangePlayMode) return false;
      if (Unk3000IEFIKMHCKDH != other.Unk3000IEFIKMHCKDH) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScreenY, other.ScreenY)) return false;
      if (IsSetFollowPos != other.IsSetFollowPos) return false;
      if (IsForce != other.IsForce) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Unk3000OGCLMFFADBD, other.Unk3000OGCLMFFADBD)) return false;
      if (EntityId != other.EntityId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScreenX, other.ScreenX)) return false;
      if (IsForceWalk != other.IsForceWalk) return false;
      if(!otherParams_.Equals(other.otherParams_)) return false;
      if (!object.Equals(FollowPos, other.FollowPos)) return false;
      if (IsAllowInput != other.IsAllowInput) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Duration, other.Duration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Unk3000MNLLCJMPMNH != 0) hash ^= Unk3000MNLLCJMPMNH.GetHashCode();
      if (Unk2700DHAHEKOGHBJ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk2700DHAHEKOGHBJ);
      if (IsSetScreenXy != false) hash ^= IsSetScreenXy.GetHashCode();
      if (lookPos_ != null) hash ^= LookPos.GetHashCode();
      if (IsRecoverKeepCurrent != false) hash ^= IsRecoverKeepCurrent.GetHashCode();
      if (Unk3000GOPIFPMFEPB != false) hash ^= Unk3000GOPIFPMFEPB.GetHashCode();
      if (Unk2700HIAKNNCKHJB != global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp) hash ^= Unk2700HIAKNNCKHJB.GetHashCode();
      if (IsChangePlayMode != false) hash ^= IsChangePlayMode.GetHashCode();
      if (Unk3000IEFIKMHCKDH != 0) hash ^= Unk3000IEFIKMHCKDH.GetHashCode();
      if (ScreenY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScreenY);
      if (IsSetFollowPos != false) hash ^= IsSetFollowPos.GetHashCode();
      if (IsForce != false) hash ^= IsForce.GetHashCode();
      if (Unk3000OGCLMFFADBD != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Unk3000OGCLMFFADBD);
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (ScreenX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScreenX);
      if (IsForceWalk != false) hash ^= IsForceWalk.GetHashCode();
      hash ^= otherParams_.GetHashCode();
      if (followPos_ != null) hash ^= FollowPos.GetHashCode();
      if (IsAllowInput != false) hash ^= IsAllowInput.GetHashCode();
      if (Duration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Duration);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      otherParams_.WriteTo(output, _repeated_otherParams_codec);
      if (IsAllowInput != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAllowInput);
      }
      if (ScreenX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(ScreenX);
      }
      if (lookPos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LookPos);
      }
      if (IsSetScreenXy != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsSetScreenXy);
      }
      if (Unk2700HIAKNNCKHJB != global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Unk2700HIAKNNCKHJB);
      }
      if (Unk2700DHAHEKOGHBJ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Unk2700DHAHEKOGHBJ);
      }
      if (followPos_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(FollowPos);
      }
      if (IsChangePlayMode != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsChangePlayMode);
      }
      if (IsForceWalk != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsForceWalk);
      }
      if (IsRecoverKeepCurrent != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsRecoverKeepCurrent);
      }
      if (IsForce != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsForce);
      }
      if (IsSetFollowPos != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsSetFollowPos);
      }
      if (Duration != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(Duration);
      }
      if (ScreenY != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(ScreenY);
      }
      if (Unk3000IEFIKMHCKDH != 0) {
        output.WriteRawTag(248, 68);
        output.WriteUInt32(Unk3000IEFIKMHCKDH);
      }
      if (Unk3000MNLLCJMPMNH != 0) {
        output.WriteRawTag(144, 72);
        output.WriteUInt32(Unk3000MNLLCJMPMNH);
      }
      if (EntityId != 0) {
        output.WriteRawTag(248, 82);
        output.WriteUInt32(EntityId);
      }
      if (Unk3000GOPIFPMFEPB != false) {
        output.WriteRawTag(248, 85);
        output.WriteBool(Unk3000GOPIFPMFEPB);
      }
      if (Unk3000OGCLMFFADBD != 0F) {
        output.WriteRawTag(245, 109);
        output.WriteFloat(Unk3000OGCLMFFADBD);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      otherParams_.WriteTo(ref output, _repeated_otherParams_codec);
      if (IsAllowInput != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsAllowInput);
      }
      if (ScreenX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(ScreenX);
      }
      if (lookPos_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LookPos);
      }
      if (IsSetScreenXy != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsSetScreenXy);
      }
      if (Unk2700HIAKNNCKHJB != global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Unk2700HIAKNNCKHJB);
      }
      if (Unk2700DHAHEKOGHBJ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Unk2700DHAHEKOGHBJ);
      }
      if (followPos_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(FollowPos);
      }
      if (IsChangePlayMode != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsChangePlayMode);
      }
      if (IsForceWalk != false) {
        output.WriteRawTag(80);
        output.WriteBool(IsForceWalk);
      }
      if (IsRecoverKeepCurrent != false) {
        output.WriteRawTag(88);
        output.WriteBool(IsRecoverKeepCurrent);
      }
      if (IsForce != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsForce);
      }
      if (IsSetFollowPos != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsSetFollowPos);
      }
      if (Duration != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(Duration);
      }
      if (ScreenY != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(ScreenY);
      }
      if (Unk3000IEFIKMHCKDH != 0) {
        output.WriteRawTag(248, 68);
        output.WriteUInt32(Unk3000IEFIKMHCKDH);
      }
      if (Unk3000MNLLCJMPMNH != 0) {
        output.WriteRawTag(144, 72);
        output.WriteUInt32(Unk3000MNLLCJMPMNH);
      }
      if (EntityId != 0) {
        output.WriteRawTag(248, 82);
        output.WriteUInt32(EntityId);
      }
      if (Unk3000GOPIFPMFEPB != false) {
        output.WriteRawTag(248, 85);
        output.WriteBool(Unk3000GOPIFPMFEPB);
      }
      if (Unk3000OGCLMFFADBD != 0F) {
        output.WriteRawTag(245, 109);
        output.WriteFloat(Unk3000OGCLMFFADBD);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Unk3000MNLLCJMPMNH != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Unk3000MNLLCJMPMNH);
      }
      if (Unk2700DHAHEKOGHBJ != 0F) {
        size += 1 + 4;
      }
      if (IsSetScreenXy != false) {
        size += 1 + 1;
      }
      if (lookPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LookPos);
      }
      if (IsRecoverKeepCurrent != false) {
        size += 1 + 1;
      }
      if (Unk3000GOPIFPMFEPB != false) {
        size += 2 + 1;
      }
      if (Unk2700HIAKNNCKHJB != global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Unk2700HIAKNNCKHJB);
      }
      if (IsChangePlayMode != false) {
        size += 1 + 1;
      }
      if (Unk3000IEFIKMHCKDH != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Unk3000IEFIKMHCKDH);
      }
      if (ScreenY != 0F) {
        size += 1 + 4;
      }
      if (IsSetFollowPos != false) {
        size += 1 + 1;
      }
      if (IsForce != false) {
        size += 1 + 1;
      }
      if (Unk3000OGCLMFFADBD != 0F) {
        size += 2 + 4;
      }
      if (EntityId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      if (ScreenX != 0F) {
        size += 1 + 4;
      }
      if (IsForceWalk != false) {
        size += 1 + 1;
      }
      size += otherParams_.CalculateSize(_repeated_otherParams_codec);
      if (followPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FollowPos);
      }
      if (IsAllowInput != false) {
        size += 1 + 1;
      }
      if (Duration != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BeginCameraSceneLookNotify other) {
      if (other == null) {
        return;
      }
      if (other.Unk3000MNLLCJMPMNH != 0) {
        Unk3000MNLLCJMPMNH = other.Unk3000MNLLCJMPMNH;
      }
      if (other.Unk2700DHAHEKOGHBJ != 0F) {
        Unk2700DHAHEKOGHBJ = other.Unk2700DHAHEKOGHBJ;
      }
      if (other.IsSetScreenXy != false) {
        IsSetScreenXy = other.IsSetScreenXy;
      }
      if (other.lookPos_ != null) {
        if (lookPos_ == null) {
          LookPos = new global::Weedwacker.Server.Proto.Vector();
        }
        LookPos.MergeFrom(other.LookPos);
      }
      if (other.IsRecoverKeepCurrent != false) {
        IsRecoverKeepCurrent = other.IsRecoverKeepCurrent;
      }
      if (other.Unk3000GOPIFPMFEPB != false) {
        Unk3000GOPIFPMFEPB = other.Unk3000GOPIFPMFEPB;
      }
      if (other.Unk2700HIAKNNCKHJB != global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD.Unk2700Acoenbmdfbp) {
        Unk2700HIAKNNCKHJB = other.Unk2700HIAKNNCKHJB;
      }
      if (other.IsChangePlayMode != false) {
        IsChangePlayMode = other.IsChangePlayMode;
      }
      if (other.Unk3000IEFIKMHCKDH != 0) {
        Unk3000IEFIKMHCKDH = other.Unk3000IEFIKMHCKDH;
      }
      if (other.ScreenY != 0F) {
        ScreenY = other.ScreenY;
      }
      if (other.IsSetFollowPos != false) {
        IsSetFollowPos = other.IsSetFollowPos;
      }
      if (other.IsForce != false) {
        IsForce = other.IsForce;
      }
      if (other.Unk3000OGCLMFFADBD != 0F) {
        Unk3000OGCLMFFADBD = other.Unk3000OGCLMFFADBD;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.ScreenX != 0F) {
        ScreenX = other.ScreenX;
      }
      if (other.IsForceWalk != false) {
        IsForceWalk = other.IsForceWalk;
      }
      otherParams_.Add(other.otherParams_);
      if (other.followPos_ != null) {
        if (followPos_ == null) {
          FollowPos = new global::Weedwacker.Server.Proto.Vector();
        }
        FollowPos.MergeFrom(other.FollowPos);
      }
      if (other.IsAllowInput != false) {
        IsAllowInput = other.IsAllowInput;
      }
      if (other.Duration != 0F) {
        Duration = other.Duration;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            otherParams_.AddEntriesFrom(input, _repeated_otherParams_codec);
            break;
          }
          case 16: {
            IsAllowInput = input.ReadBool();
            break;
          }
          case 29: {
            ScreenX = input.ReadFloat();
            break;
          }
          case 34: {
            if (lookPos_ == null) {
              LookPos = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(LookPos);
            break;
          }
          case 40: {
            IsSetScreenXy = input.ReadBool();
            break;
          }
          case 48: {
            Unk2700HIAKNNCKHJB = (global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD) input.ReadEnum();
            break;
          }
          case 61: {
            Unk2700DHAHEKOGHBJ = input.ReadFloat();
            break;
          }
          case 66: {
            if (followPos_ == null) {
              FollowPos = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(FollowPos);
            break;
          }
          case 72: {
            IsChangePlayMode = input.ReadBool();
            break;
          }
          case 80: {
            IsForceWalk = input.ReadBool();
            break;
          }
          case 88: {
            IsRecoverKeepCurrent = input.ReadBool();
            break;
          }
          case 96: {
            IsForce = input.ReadBool();
            break;
          }
          case 104: {
            IsSetFollowPos = input.ReadBool();
            break;
          }
          case 117: {
            Duration = input.ReadFloat();
            break;
          }
          case 125: {
            ScreenY = input.ReadFloat();
            break;
          }
          case 8824: {
            Unk3000IEFIKMHCKDH = input.ReadUInt32();
            break;
          }
          case 9232: {
            Unk3000MNLLCJMPMNH = input.ReadUInt32();
            break;
          }
          case 10616: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 11000: {
            Unk3000GOPIFPMFEPB = input.ReadBool();
            break;
          }
          case 14069: {
            Unk3000OGCLMFFADBD = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            otherParams_.AddEntriesFrom(ref input, _repeated_otherParams_codec);
            break;
          }
          case 16: {
            IsAllowInput = input.ReadBool();
            break;
          }
          case 29: {
            ScreenX = input.ReadFloat();
            break;
          }
          case 34: {
            if (lookPos_ == null) {
              LookPos = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(LookPos);
            break;
          }
          case 40: {
            IsSetScreenXy = input.ReadBool();
            break;
          }
          case 48: {
            Unk2700HIAKNNCKHJB = (global::Weedwacker.Server.Proto.BeginCameraSceneLookNotify.Types.Unk2700_LNCHDDOOECD) input.ReadEnum();
            break;
          }
          case 61: {
            Unk2700DHAHEKOGHBJ = input.ReadFloat();
            break;
          }
          case 66: {
            if (followPos_ == null) {
              FollowPos = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(FollowPos);
            break;
          }
          case 72: {
            IsChangePlayMode = input.ReadBool();
            break;
          }
          case 80: {
            IsForceWalk = input.ReadBool();
            break;
          }
          case 88: {
            IsRecoverKeepCurrent = input.ReadBool();
            break;
          }
          case 96: {
            IsForce = input.ReadBool();
            break;
          }
          case 104: {
            IsSetFollowPos = input.ReadBool();
            break;
          }
          case 117: {
            Duration = input.ReadFloat();
            break;
          }
          case 125: {
            ScreenY = input.ReadFloat();
            break;
          }
          case 8824: {
            Unk3000IEFIKMHCKDH = input.ReadUInt32();
            break;
          }
          case 9232: {
            Unk3000MNLLCJMPMNH = input.ReadUInt32();
            break;
          }
          case 10616: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 11000: {
            Unk3000GOPIFPMFEPB = input.ReadBool();
            break;
          }
          case 14069: {
            Unk3000OGCLMFFADBD = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BeginCameraSceneLookNotify message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Unk2700_LNCHDDOOECD {
        [pbr::OriginalName("Unk2700_LNCHDDOOECD_Unk2700_ACOENBMDFBP")] Unk2700Acoenbmdfbp = 0,
        [pbr::OriginalName("Unk2700_LNCHDDOOECD_Unk2700_FKBLCDFLCOM")] Unk2700Fkblcdflcom = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
