// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IrodoriChessSettleInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from IrodoriChessSettleInfo.proto</summary>
  public static partial class IrodoriChessSettleInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for IrodoriChessSettleInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IrodoriChessSettleInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxJcm9kb3JpQ2hlc3NTZXR0bGVJbmZvLnByb3RvIq4BChZJcm9kb3JpQ2hl",
            "c3NTZXR0bGVJbmZvEhUKDWlzX25ld19yZWNvcmQYBSABKAgSGwoTVW5rMjcw",
            "MF9QRkVEUExLS0xHSBgCIAEoCBIVCg1zY2VuZV90aW1lX21zGAEgASgEEhsK",
            "E1VuazI3MDBfQ0RPS0VOSkpKTUgYAyABKA0SEgoKaXNfcGVyZmVjdBgMIAEo",
            "CBIYChBraWxsX21vbnN0ZXJfbnVtGAcgASgNQhqqAhdXZWVkd2Fja2VyLlNl",
            "cnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.IrodoriChessSettleInfo), global::Weedwacker.Server.Proto.IrodoriChessSettleInfo.Parser, new[]{ "IsNewRecord", "Unk2700PFEDPLKKLGH", "SceneTimeMs", "Unk2700CDOKENJJJMH", "IsPerfect", "KillMonsterNum" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class IrodoriChessSettleInfo : pb::IMessage<IrodoriChessSettleInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IrodoriChessSettleInfo> _parser = new pb::MessageParser<IrodoriChessSettleInfo>(() => new IrodoriChessSettleInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IrodoriChessSettleInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.IrodoriChessSettleInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IrodoriChessSettleInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IrodoriChessSettleInfo(IrodoriChessSettleInfo other) : this() {
      isNewRecord_ = other.isNewRecord_;
      unk2700PFEDPLKKLGH_ = other.unk2700PFEDPLKKLGH_;
      sceneTimeMs_ = other.sceneTimeMs_;
      unk2700CDOKENJJJMH_ = other.unk2700CDOKENJJJMH_;
      isPerfect_ = other.isPerfect_;
      killMonsterNum_ = other.killMonsterNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IrodoriChessSettleInfo Clone() {
      return new IrodoriChessSettleInfo(this);
    }

    /// <summary>Field number for the "is_new_record" field.</summary>
    public const int IsNewRecordFieldNumber = 5;
    private bool isNewRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewRecord {
      get { return isNewRecord_; }
      set {
        isNewRecord_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_PFEDPLKKLGH" field.</summary>
    public const int Unk2700PFEDPLKKLGHFieldNumber = 2;
    private bool unk2700PFEDPLKKLGH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk2700PFEDPLKKLGH {
      get { return unk2700PFEDPLKKLGH_; }
      set {
        unk2700PFEDPLKKLGH_ = value;
      }
    }

    /// <summary>Field number for the "scene_time_ms" field.</summary>
    public const int SceneTimeMsFieldNumber = 1;
    private ulong sceneTimeMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SceneTimeMs {
      get { return sceneTimeMs_; }
      set {
        sceneTimeMs_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_CDOKENJJJMH" field.</summary>
    public const int Unk2700CDOKENJJJMHFieldNumber = 3;
    private uint unk2700CDOKENJJJMH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700CDOKENJJJMH {
      get { return unk2700CDOKENJJJMH_; }
      set {
        unk2700CDOKENJJJMH_ = value;
      }
    }

    /// <summary>Field number for the "is_perfect" field.</summary>
    public const int IsPerfectFieldNumber = 12;
    private bool isPerfect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPerfect {
      get { return isPerfect_; }
      set {
        isPerfect_ = value;
      }
    }

    /// <summary>Field number for the "kill_monster_num" field.</summary>
    public const int KillMonsterNumFieldNumber = 7;
    private uint killMonsterNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KillMonsterNum {
      get { return killMonsterNum_; }
      set {
        killMonsterNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IrodoriChessSettleInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IrodoriChessSettleInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsNewRecord != other.IsNewRecord) return false;
      if (Unk2700PFEDPLKKLGH != other.Unk2700PFEDPLKKLGH) return false;
      if (SceneTimeMs != other.SceneTimeMs) return false;
      if (Unk2700CDOKENJJJMH != other.Unk2700CDOKENJJJMH) return false;
      if (IsPerfect != other.IsPerfect) return false;
      if (KillMonsterNum != other.KillMonsterNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsNewRecord != false) hash ^= IsNewRecord.GetHashCode();
      if (Unk2700PFEDPLKKLGH != false) hash ^= Unk2700PFEDPLKKLGH.GetHashCode();
      if (SceneTimeMs != 0UL) hash ^= SceneTimeMs.GetHashCode();
      if (Unk2700CDOKENJJJMH != 0) hash ^= Unk2700CDOKENJJJMH.GetHashCode();
      if (IsPerfect != false) hash ^= IsPerfect.GetHashCode();
      if (KillMonsterNum != 0) hash ^= KillMonsterNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneTimeMs != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SceneTimeMs);
      }
      if (Unk2700PFEDPLKKLGH != false) {
        output.WriteRawTag(16);
        output.WriteBool(Unk2700PFEDPLKKLGH);
      }
      if (Unk2700CDOKENJJJMH != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk2700CDOKENJJJMH);
      }
      if (IsNewRecord != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsNewRecord);
      }
      if (KillMonsterNum != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KillMonsterNum);
      }
      if (IsPerfect != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsPerfect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneTimeMs != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(SceneTimeMs);
      }
      if (Unk2700PFEDPLKKLGH != false) {
        output.WriteRawTag(16);
        output.WriteBool(Unk2700PFEDPLKKLGH);
      }
      if (Unk2700CDOKENJJJMH != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk2700CDOKENJJJMH);
      }
      if (IsNewRecord != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsNewRecord);
      }
      if (KillMonsterNum != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KillMonsterNum);
      }
      if (IsPerfect != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsPerfect);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsNewRecord != false) {
        size += 1 + 1;
      }
      if (Unk2700PFEDPLKKLGH != false) {
        size += 1 + 1;
      }
      if (SceneTimeMs != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SceneTimeMs);
      }
      if (Unk2700CDOKENJJJMH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700CDOKENJJJMH);
      }
      if (IsPerfect != false) {
        size += 1 + 1;
      }
      if (KillMonsterNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KillMonsterNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IrodoriChessSettleInfo other) {
      if (other == null) {
        return;
      }
      if (other.IsNewRecord != false) {
        IsNewRecord = other.IsNewRecord;
      }
      if (other.Unk2700PFEDPLKKLGH != false) {
        Unk2700PFEDPLKKLGH = other.Unk2700PFEDPLKKLGH;
      }
      if (other.SceneTimeMs != 0UL) {
        SceneTimeMs = other.SceneTimeMs;
      }
      if (other.Unk2700CDOKENJJJMH != 0) {
        Unk2700CDOKENJJJMH = other.Unk2700CDOKENJJJMH;
      }
      if (other.IsPerfect != false) {
        IsPerfect = other.IsPerfect;
      }
      if (other.KillMonsterNum != 0) {
        KillMonsterNum = other.KillMonsterNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SceneTimeMs = input.ReadUInt64();
            break;
          }
          case 16: {
            Unk2700PFEDPLKKLGH = input.ReadBool();
            break;
          }
          case 24: {
            Unk2700CDOKENJJJMH = input.ReadUInt32();
            break;
          }
          case 40: {
            IsNewRecord = input.ReadBool();
            break;
          }
          case 56: {
            KillMonsterNum = input.ReadUInt32();
            break;
          }
          case 96: {
            IsPerfect = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SceneTimeMs = input.ReadUInt64();
            break;
          }
          case 16: {
            Unk2700PFEDPLKKLGH = input.ReadBool();
            break;
          }
          case 24: {
            Unk2700CDOKENJJJMH = input.ReadUInt32();
            break;
          }
          case 40: {
            IsNewRecord = input.ReadBool();
            break;
          }
          case 56: {
            KillMonsterNum = input.ReadUInt32();
            break;
          }
          case 96: {
            IsPerfect = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
