// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PhotoStage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from PhotoStage.proto</summary>
  public static partial class PhotoStageReflection {

    #region Descriptor
    /// <summary>File descriptor for PhotoStage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PhotoStageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQaG90b1N0YWdlLnByb3RvGgxWZWN0b3IucHJvdG8igwEKClBob3RvU3Rh",
            "Z2USFwoGY2VudGVyGA8gASgLMgcuVmVjdG9yEhEKCW9wZW5fdGltZRgCIAEo",
            "DRIbChNVbmsyNzAwX0RET0JOS0xMTERGGAQgASgIEhsKE1VuazI3MDBfQ0tH",
            "SkVPT0tGSUYYCSABKA0SDwoHaXNfb3BlbhgGIAEoCEIaqgIXV2VlZHdhY2tl",
            "ci5TZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Server.Proto.VectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.PhotoStage), global::Weedwacker.Server.Proto.PhotoStage.Parser, new[]{ "Center", "OpenTime", "Unk2700DDOBNKLLLDF", "Unk2700CKGJEOOKFIF", "IsOpen" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PhotoStage : pb::IMessage<PhotoStage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PhotoStage> _parser = new pb::MessageParser<PhotoStage>(() => new PhotoStage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PhotoStage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.PhotoStageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhotoStage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhotoStage(PhotoStage other) : this() {
      center_ = other.center_ != null ? other.center_.Clone() : null;
      openTime_ = other.openTime_;
      unk2700DDOBNKLLLDF_ = other.unk2700DDOBNKLLLDF_;
      unk2700CKGJEOOKFIF_ = other.unk2700CKGJEOOKFIF_;
      isOpen_ = other.isOpen_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhotoStage Clone() {
      return new PhotoStage(this);
    }

    /// <summary>Field number for the "center" field.</summary>
    public const int CenterFieldNumber = 15;
    private global::Weedwacker.Server.Proto.Vector center_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Vector Center {
      get { return center_; }
      set {
        center_ = value;
      }
    }

    /// <summary>Field number for the "open_time" field.</summary>
    public const int OpenTimeFieldNumber = 2;
    private uint openTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OpenTime {
      get { return openTime_; }
      set {
        openTime_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_DDOBNKLLLDF" field.</summary>
    public const int Unk2700DDOBNKLLLDFFieldNumber = 4;
    private bool unk2700DDOBNKLLLDF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk2700DDOBNKLLLDF {
      get { return unk2700DDOBNKLLLDF_; }
      set {
        unk2700DDOBNKLLLDF_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_CKGJEOOKFIF" field.</summary>
    public const int Unk2700CKGJEOOKFIFFieldNumber = 9;
    private uint unk2700CKGJEOOKFIF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700CKGJEOOKFIF {
      get { return unk2700CKGJEOOKFIF_; }
      set {
        unk2700CKGJEOOKFIF_ = value;
      }
    }

    /// <summary>Field number for the "is_open" field.</summary>
    public const int IsOpenFieldNumber = 6;
    private bool isOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOpen {
      get { return isOpen_; }
      set {
        isOpen_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PhotoStage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PhotoStage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Center, other.Center)) return false;
      if (OpenTime != other.OpenTime) return false;
      if (Unk2700DDOBNKLLLDF != other.Unk2700DDOBNKLLLDF) return false;
      if (Unk2700CKGJEOOKFIF != other.Unk2700CKGJEOOKFIF) return false;
      if (IsOpen != other.IsOpen) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (center_ != null) hash ^= Center.GetHashCode();
      if (OpenTime != 0) hash ^= OpenTime.GetHashCode();
      if (Unk2700DDOBNKLLLDF != false) hash ^= Unk2700DDOBNKLLLDF.GetHashCode();
      if (Unk2700CKGJEOOKFIF != 0) hash ^= Unk2700CKGJEOOKFIF.GetHashCode();
      if (IsOpen != false) hash ^= IsOpen.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OpenTime != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(OpenTime);
      }
      if (Unk2700DDOBNKLLLDF != false) {
        output.WriteRawTag(32);
        output.WriteBool(Unk2700DDOBNKLLLDF);
      }
      if (IsOpen != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOpen);
      }
      if (Unk2700CKGJEOOKFIF != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Unk2700CKGJEOOKFIF);
      }
      if (center_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Center);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OpenTime != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(OpenTime);
      }
      if (Unk2700DDOBNKLLLDF != false) {
        output.WriteRawTag(32);
        output.WriteBool(Unk2700DDOBNKLLLDF);
      }
      if (IsOpen != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOpen);
      }
      if (Unk2700CKGJEOOKFIF != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Unk2700CKGJEOOKFIF);
      }
      if (center_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Center);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (center_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Center);
      }
      if (OpenTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OpenTime);
      }
      if (Unk2700DDOBNKLLLDF != false) {
        size += 1 + 1;
      }
      if (Unk2700CKGJEOOKFIF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700CKGJEOOKFIF);
      }
      if (IsOpen != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PhotoStage other) {
      if (other == null) {
        return;
      }
      if (other.center_ != null) {
        if (center_ == null) {
          Center = new global::Weedwacker.Server.Proto.Vector();
        }
        Center.MergeFrom(other.Center);
      }
      if (other.OpenTime != 0) {
        OpenTime = other.OpenTime;
      }
      if (other.Unk2700DDOBNKLLLDF != false) {
        Unk2700DDOBNKLLLDF = other.Unk2700DDOBNKLLLDF;
      }
      if (other.Unk2700CKGJEOOKFIF != 0) {
        Unk2700CKGJEOOKFIF = other.Unk2700CKGJEOOKFIF;
      }
      if (other.IsOpen != false) {
        IsOpen = other.IsOpen;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            OpenTime = input.ReadUInt32();
            break;
          }
          case 32: {
            Unk2700DDOBNKLLLDF = input.ReadBool();
            break;
          }
          case 48: {
            IsOpen = input.ReadBool();
            break;
          }
          case 72: {
            Unk2700CKGJEOOKFIF = input.ReadUInt32();
            break;
          }
          case 122: {
            if (center_ == null) {
              Center = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(Center);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            OpenTime = input.ReadUInt32();
            break;
          }
          case 32: {
            Unk2700DDOBNKLLLDF = input.ReadBool();
            break;
          }
          case 48: {
            IsOpen = input.ReadBool();
            break;
          }
          case 72: {
            Unk2700CKGJEOOKFIF = input.ReadUInt32();
            break;
          }
          case 122: {
            if (center_ == null) {
              Center = new global::Weedwacker.Server.Proto.Vector();
            }
            input.ReadMessage(Center);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
