// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Unk2800_GDDLBKEENNA.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from Unk2800_GDDLBKEENNA.proto</summary>
  public static partial class Unk2800GDDLBKEENNAReflection {

    #region Descriptor
    /// <summary>File descriptor for Unk2800_GDDLBKEENNA.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Unk2800GDDLBKEENNAReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVbmsyODAwX0dERExCS0VFTk5BLnByb3RvGhtFeGhpYml0aW9uRGlzcGxh",
            "eUluZm8ucHJvdG8aGVVuazI3MDBfTU9GQUJQTkdJS1AucHJvdG8aGVVuazI4",
            "MDBfQkVNQU5EQk5QSkIucHJvdG8iywEKE1VuazI4MDBfR0RETEJLRUVOTkES",
            "FQoNaXNfbmV3X3JlY29yZBgNIAEoCBIkCgZyZWFzb24YASABKA4yFC5Vbmsy",
            "NzAwX01PRkFCUE5HSUtQEi4KEHNldHRsZV9pbmZvX2xpc3QYCCADKAsyFC5V",
            "bmsyODAwX0JFTUFOREJOUEpCEioKCnNjb3JlX2xpc3QYBiADKAsyFi5FeGhp",
            "Yml0aW9uRGlzcGxheUluZm8SGwoTVW5rMjcwMF9DRERPTkpKTUZDSRgPIAEo",
            "DUIaqgIXV2VlZHdhY2tlci5TZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Weedwacker.Server.Proto.ExhibitionDisplayInfoReflection.Descriptor, global::Weedwacker.Server.Proto.Unk2700MOFABPNGIKPReflection.Descriptor, global::Weedwacker.Server.Proto.Unk2800BEMANDBNPJBReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.Unk2800_GDDLBKEENNA), global::Weedwacker.Server.Proto.Unk2800_GDDLBKEENNA.Parser, new[]{ "IsNewRecord", "Reason", "SettleInfoList", "ScoreList", "Unk2700CDDONJJMFCI" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// CmdId: 24601
  /// EnetChannelId: 0
  /// EnetIsReliable: true
  /// </summary>
  public sealed partial class Unk2800_GDDLBKEENNA : pb::IMessage<Unk2800_GDDLBKEENNA>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Unk2800_GDDLBKEENNA> _parser = new pb::MessageParser<Unk2800_GDDLBKEENNA>(() => new Unk2800_GDDLBKEENNA());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Unk2800_GDDLBKEENNA> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.Unk2800GDDLBKEENNAReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2800_GDDLBKEENNA() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2800_GDDLBKEENNA(Unk2800_GDDLBKEENNA other) : this() {
      isNewRecord_ = other.isNewRecord_;
      reason_ = other.reason_;
      settleInfoList_ = other.settleInfoList_.Clone();
      scoreList_ = other.scoreList_.Clone();
      unk2700CDDONJJMFCI_ = other.unk2700CDDONJJMFCI_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2800_GDDLBKEENNA Clone() {
      return new Unk2800_GDDLBKEENNA(this);
    }

    /// <summary>Field number for the "is_new_record" field.</summary>
    public const int IsNewRecordFieldNumber = 13;
    private bool isNewRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewRecord {
      get { return isNewRecord_; }
      set {
        isNewRecord_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP reason_ = global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "settle_info_list" field.</summary>
    public const int SettleInfoListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Weedwacker.Server.Proto.Unk2800_BEMANDBNPJB> _repeated_settleInfoList_codec
        = pb::FieldCodec.ForMessage(66, global::Weedwacker.Server.Proto.Unk2800_BEMANDBNPJB.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Server.Proto.Unk2800_BEMANDBNPJB> settleInfoList_ = new pbc::RepeatedField<global::Weedwacker.Server.Proto.Unk2800_BEMANDBNPJB>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Server.Proto.Unk2800_BEMANDBNPJB> SettleInfoList {
      get { return settleInfoList_; }
    }

    /// <summary>Field number for the "score_list" field.</summary>
    public const int ScoreListFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Weedwacker.Server.Proto.ExhibitionDisplayInfo> _repeated_scoreList_codec
        = pb::FieldCodec.ForMessage(50, global::Weedwacker.Server.Proto.ExhibitionDisplayInfo.Parser);
    private readonly pbc::RepeatedField<global::Weedwacker.Server.Proto.ExhibitionDisplayInfo> scoreList_ = new pbc::RepeatedField<global::Weedwacker.Server.Proto.ExhibitionDisplayInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Weedwacker.Server.Proto.ExhibitionDisplayInfo> ScoreList {
      get { return scoreList_; }
    }

    /// <summary>Field number for the "Unk2700_CDDONJJMFCI" field.</summary>
    public const int Unk2700CDDONJJMFCIFieldNumber = 15;
    private uint unk2700CDDONJJMFCI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700CDDONJJMFCI {
      get { return unk2700CDDONJJMFCI_; }
      set {
        unk2700CDDONJJMFCI_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Unk2800_GDDLBKEENNA);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Unk2800_GDDLBKEENNA other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsNewRecord != other.IsNewRecord) return false;
      if (Reason != other.Reason) return false;
      if(!settleInfoList_.Equals(other.settleInfoList_)) return false;
      if(!scoreList_.Equals(other.scoreList_)) return false;
      if (Unk2700CDDONJJMFCI != other.Unk2700CDDONJJMFCI) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsNewRecord != false) hash ^= IsNewRecord.GetHashCode();
      if (Reason != global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj) hash ^= Reason.GetHashCode();
      hash ^= settleInfoList_.GetHashCode();
      hash ^= scoreList_.GetHashCode();
      if (Unk2700CDDONJJMFCI != 0) hash ^= Unk2700CDDONJJMFCI.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reason != global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      scoreList_.WriteTo(output, _repeated_scoreList_codec);
      settleInfoList_.WriteTo(output, _repeated_settleInfoList_codec);
      if (IsNewRecord != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsNewRecord);
      }
      if (Unk2700CDDONJJMFCI != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Unk2700CDDONJJMFCI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reason != global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      scoreList_.WriteTo(ref output, _repeated_scoreList_codec);
      settleInfoList_.WriteTo(ref output, _repeated_settleInfoList_codec);
      if (IsNewRecord != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsNewRecord);
      }
      if (Unk2700CDDONJJMFCI != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Unk2700CDDONJJMFCI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsNewRecord != false) {
        size += 1 + 1;
      }
      if (Reason != global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      size += settleInfoList_.CalculateSize(_repeated_settleInfoList_codec);
      size += scoreList_.CalculateSize(_repeated_scoreList_codec);
      if (Unk2700CDDONJJMFCI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700CDDONJJMFCI);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Unk2800_GDDLBKEENNA other) {
      if (other == null) {
        return;
      }
      if (other.IsNewRecord != false) {
        IsNewRecord = other.IsNewRecord;
      }
      if (other.Reason != global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP.Unk2700Dgjfkkiblcj) {
        Reason = other.Reason;
      }
      settleInfoList_.Add(other.settleInfoList_);
      scoreList_.Add(other.scoreList_);
      if (other.Unk2700CDDONJJMFCI != 0) {
        Unk2700CDDONJJMFCI = other.Unk2700CDDONJJMFCI;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = (global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP) input.ReadEnum();
            break;
          }
          case 50: {
            scoreList_.AddEntriesFrom(input, _repeated_scoreList_codec);
            break;
          }
          case 66: {
            settleInfoList_.AddEntriesFrom(input, _repeated_settleInfoList_codec);
            break;
          }
          case 104: {
            IsNewRecord = input.ReadBool();
            break;
          }
          case 120: {
            Unk2700CDDONJJMFCI = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Reason = (global::Weedwacker.Server.Proto.Unk2700_MOFABPNGIKP) input.ReadEnum();
            break;
          }
          case 50: {
            scoreList_.AddEntriesFrom(ref input, _repeated_scoreList_codec);
            break;
          }
          case 66: {
            settleInfoList_.AddEntriesFrom(ref input, _repeated_settleInfoList_codec);
            break;
          }
          case 104: {
            IsNewRecord = input.ReadBool();
            break;
          }
          case 120: {
            Unk2700CDDONJJMFCI = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
