// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Unk2700_ELMEOJFCOFH.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Weedwacker.Server.Proto {

  /// <summary>Holder for reflection information generated from Unk2700_ELMEOJFCOFH.proto</summary>
  public static partial class Unk2700ELMEOJFCOFHReflection {

    #region Descriptor
    /// <summary>File descriptor for Unk2700_ELMEOJFCOFH.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Unk2700ELMEOJFCOFHReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVbmsyNzAwX0VMTUVPSkZDT0ZILnByb3RvIo8CChNVbmsyNzAwX0VMTUVP",
            "SkZDT0ZIEkkKE1VuazI3MDBfSEdCTklGQUtPR0kYDCADKAsyLC5VbmsyNzAw",
            "X0VMTUVPSkZDT0ZILlVuazI3MDBIR0JOSUZBS09HSUVudHJ5EhsKE1VuazI3",
            "MDBfQlBERkpKTkpHQUoYAyABKA0SGwoTVW5rMjcwMF9EQ0JPSUZKQ0RIRxgP",
            "IAEoDRIbChNVbmsyNzAwX0tESkdEUERKSExMGAYgASgNEhsKE1VuazI3MDBf",
            "TkdLR0pKQkRHTVAYByABKA0aOQoXVW5rMjcwMEhHQk5JRkFLT0dJRW50cnkS",
            "CwoDa2V5GAEgASgNEg0KBXZhbHVlGAIgASgNOgI4AUIaqgIXV2VlZHdhY2tl",
            "ci5TZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Weedwacker.Server.Proto.Unk2700_ELMEOJFCOFH), global::Weedwacker.Server.Proto.Unk2700_ELMEOJFCOFH.Parser, new[]{ "Unk2700HGBNIFAKOGI", "Unk2700BPDFJJNJGAJ", "Unk2700DCBOIFJCDHG", "Unk2700KDJGDPDJHLL", "Unk2700NGKGJJBDGMP" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Unk2700_ELMEOJFCOFH : pb::IMessage<Unk2700_ELMEOJFCOFH>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Unk2700_ELMEOJFCOFH> _parser = new pb::MessageParser<Unk2700_ELMEOJFCOFH>(() => new Unk2700_ELMEOJFCOFH());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Unk2700_ELMEOJFCOFH> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Weedwacker.Server.Proto.Unk2700ELMEOJFCOFHReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_ELMEOJFCOFH() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_ELMEOJFCOFH(Unk2700_ELMEOJFCOFH other) : this() {
      unk2700HGBNIFAKOGI_ = other.unk2700HGBNIFAKOGI_.Clone();
      unk2700BPDFJJNJGAJ_ = other.unk2700BPDFJJNJGAJ_;
      unk2700DCBOIFJCDHG_ = other.unk2700DCBOIFJCDHG_;
      unk2700KDJGDPDJHLL_ = other.unk2700KDJGDPDJHLL_;
      unk2700NGKGJJBDGMP_ = other.unk2700NGKGJJBDGMP_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Unk2700_ELMEOJFCOFH Clone() {
      return new Unk2700_ELMEOJFCOFH(this);
    }

    /// <summary>Field number for the "Unk2700_HGBNIFAKOGI" field.</summary>
    public const int Unk2700HGBNIFAKOGIFieldNumber = 12;
    private static readonly pbc::MapField<uint, uint>.Codec _map_unk2700HGBNIFAKOGI_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 98);
    private readonly pbc::MapField<uint, uint> unk2700HGBNIFAKOGI_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> Unk2700HGBNIFAKOGI {
      get { return unk2700HGBNIFAKOGI_; }
    }

    /// <summary>Field number for the "Unk2700_BPDFJJNJGAJ" field.</summary>
    public const int Unk2700BPDFJJNJGAJFieldNumber = 3;
    private uint unk2700BPDFJJNJGAJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700BPDFJJNJGAJ {
      get { return unk2700BPDFJJNJGAJ_; }
      set {
        unk2700BPDFJJNJGAJ_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_DCBOIFJCDHG" field.</summary>
    public const int Unk2700DCBOIFJCDHGFieldNumber = 15;
    private uint unk2700DCBOIFJCDHG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700DCBOIFJCDHG {
      get { return unk2700DCBOIFJCDHG_; }
      set {
        unk2700DCBOIFJCDHG_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_KDJGDPDJHLL" field.</summary>
    public const int Unk2700KDJGDPDJHLLFieldNumber = 6;
    private uint unk2700KDJGDPDJHLL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700KDJGDPDJHLL {
      get { return unk2700KDJGDPDJHLL_; }
      set {
        unk2700KDJGDPDJHLL_ = value;
      }
    }

    /// <summary>Field number for the "Unk2700_NGKGJJBDGMP" field.</summary>
    public const int Unk2700NGKGJJBDGMPFieldNumber = 7;
    private uint unk2700NGKGJJBDGMP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Unk2700NGKGJJBDGMP {
      get { return unk2700NGKGJJBDGMP_; }
      set {
        unk2700NGKGJJBDGMP_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Unk2700_ELMEOJFCOFH);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Unk2700_ELMEOJFCOFH other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Unk2700HGBNIFAKOGI.Equals(other.Unk2700HGBNIFAKOGI)) return false;
      if (Unk2700BPDFJJNJGAJ != other.Unk2700BPDFJJNJGAJ) return false;
      if (Unk2700DCBOIFJCDHG != other.Unk2700DCBOIFJCDHG) return false;
      if (Unk2700KDJGDPDJHLL != other.Unk2700KDJGDPDJHLL) return false;
      if (Unk2700NGKGJJBDGMP != other.Unk2700NGKGJJBDGMP) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Unk2700HGBNIFAKOGI.GetHashCode();
      if (Unk2700BPDFJJNJGAJ != 0) hash ^= Unk2700BPDFJJNJGAJ.GetHashCode();
      if (Unk2700DCBOIFJCDHG != 0) hash ^= Unk2700DCBOIFJCDHG.GetHashCode();
      if (Unk2700KDJGDPDJHLL != 0) hash ^= Unk2700KDJGDPDJHLL.GetHashCode();
      if (Unk2700NGKGJJBDGMP != 0) hash ^= Unk2700NGKGJJBDGMP.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Unk2700BPDFJJNJGAJ != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk2700BPDFJJNJGAJ);
      }
      if (Unk2700KDJGDPDJHLL != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Unk2700KDJGDPDJHLL);
      }
      if (Unk2700NGKGJJBDGMP != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Unk2700NGKGJJBDGMP);
      }
      unk2700HGBNIFAKOGI_.WriteTo(output, _map_unk2700HGBNIFAKOGI_codec);
      if (Unk2700DCBOIFJCDHG != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Unk2700DCBOIFJCDHG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Unk2700BPDFJJNJGAJ != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Unk2700BPDFJJNJGAJ);
      }
      if (Unk2700KDJGDPDJHLL != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Unk2700KDJGDPDJHLL);
      }
      if (Unk2700NGKGJJBDGMP != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Unk2700NGKGJJBDGMP);
      }
      unk2700HGBNIFAKOGI_.WriteTo(ref output, _map_unk2700HGBNIFAKOGI_codec);
      if (Unk2700DCBOIFJCDHG != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(Unk2700DCBOIFJCDHG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += unk2700HGBNIFAKOGI_.CalculateSize(_map_unk2700HGBNIFAKOGI_codec);
      if (Unk2700BPDFJJNJGAJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700BPDFJJNJGAJ);
      }
      if (Unk2700DCBOIFJCDHG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700DCBOIFJCDHG);
      }
      if (Unk2700KDJGDPDJHLL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700KDJGDPDJHLL);
      }
      if (Unk2700NGKGJJBDGMP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Unk2700NGKGJJBDGMP);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Unk2700_ELMEOJFCOFH other) {
      if (other == null) {
        return;
      }
      unk2700HGBNIFAKOGI_.Add(other.unk2700HGBNIFAKOGI_);
      if (other.Unk2700BPDFJJNJGAJ != 0) {
        Unk2700BPDFJJNJGAJ = other.Unk2700BPDFJJNJGAJ;
      }
      if (other.Unk2700DCBOIFJCDHG != 0) {
        Unk2700DCBOIFJCDHG = other.Unk2700DCBOIFJCDHG;
      }
      if (other.Unk2700KDJGDPDJHLL != 0) {
        Unk2700KDJGDPDJHLL = other.Unk2700KDJGDPDJHLL;
      }
      if (other.Unk2700NGKGJJBDGMP != 0) {
        Unk2700NGKGJJBDGMP = other.Unk2700NGKGJJBDGMP;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            Unk2700BPDFJJNJGAJ = input.ReadUInt32();
            break;
          }
          case 48: {
            Unk2700KDJGDPDJHLL = input.ReadUInt32();
            break;
          }
          case 56: {
            Unk2700NGKGJJBDGMP = input.ReadUInt32();
            break;
          }
          case 98: {
            unk2700HGBNIFAKOGI_.AddEntriesFrom(input, _map_unk2700HGBNIFAKOGI_codec);
            break;
          }
          case 120: {
            Unk2700DCBOIFJCDHG = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            Unk2700BPDFJJNJGAJ = input.ReadUInt32();
            break;
          }
          case 48: {
            Unk2700KDJGDPDJHLL = input.ReadUInt32();
            break;
          }
          case 56: {
            Unk2700NGKGJJBDGMP = input.ReadUInt32();
            break;
          }
          case 98: {
            unk2700HGBNIFAKOGI_.AddEntriesFrom(ref input, _map_unk2700HGBNIFAKOGI_codec);
            break;
          }
          case 120: {
            Unk2700DCBOIFJCDHG = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
